### ISSUE TITLE
Prevent Default Behavior of Gesture (Back Navigation on Mobile)

### ISSUE THREAD

**Issue by mjsisley** [react-spring/react-use-gesture#1]
On mobile browsers (at least on iOS: Safari, Chrome), I'm getting the default behavior of a swipe to the left triggering a back navigation (along with the gesture provided with this library). It would be great if this library exposed a way to prevent that default behavior.

I see you removed `preventDefault` on the last release, I'm not sure what the issue was... but it would be great if there was some way to configure this (I'm not seeing one atm).

**Comment by drcmda** [comment]
@mjsisley i think i got some console warnings in chrome, didn't they change the way events worked? I'm a bit out of the loop, do you know what would be the *right* way to do it? Would you go for an option, or use a reasonable default.

**Comment by zvictor** [comment]
I am having a similar issue with Chrome reloading the page when I swipe down. Having the ability to stopPropagation/preventDefault is a must 🤳

At first I tried using `onAction` to achieve this goal, expecting it to send down the event, but that's not possible. So, my proposal is that we change the api to expose `event` somehow.

```js
// proposal A
//  send `event` as extra argument in `onAction`
useGesture({ onAction: (props, event) => event.preventDefault() })


// proposal B
//  provide exclusive handler for `event`
useGesture({ onEvent: event => event.preventDefault() })
```

**Comment by drcmda** [comment]
Makes sense, the event is now included in 3.0.3. I've switched it to passive mode, though, so in order to be able to do e.preventDefault it would be something like this:

    useEvent({ transient: true, onAction: props => props.event.preventDefault(), passive: false })

**Comment by niwsa** [comment]
@drcmda Is it possible to preventDefault in render props pattern? I don't quite understand transient mode, how are things different in transient mode will something like below work ?

![code](https://user-images.githubusercontent.com/3107922/50582871-a8fe6c80-0e8b-11e9-988e-ca1e6c519ac3.png)

**Comment by drcmda** [comment]
Yeah, I noticed, there’s no way currently to pass props. I think it would be a breaking change at for the HOC. Should we do it?

**Comment by niwsa** [comment]
Seems yes from my side.I am facing the same issue that Victor faces i.e the browser refreshing the page on swiping down.Hopefully the breaking change you mentioned won't cause issues somewhere else or do they (I don't have the whole picture)?

**Comment by zvictor** [comment]
thanks for the great and quick work, @drcmda!
I pushed a little as #18 and I would like to also make a comment about the `passive` prop added by you.

I think the code you posted above contains some imprecisions. Wouldn't the correct way be as below?
```js
useGesture({ transient: true, onAction: props => props.event.preventDefault(), passive: {passive: false} })
```

If my understanding of the code is correct we are sending the prop `passive`, as it is, down as the third argument of [addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters), which is called `options` there. I would then recommend calling this prop something that relates to its original name, e.g. `listenerOptions` or just `options`.

```js
useGesture({ transient: true, onAction: props => props.event.preventDefault(), options: {passive: false} })
```

**Comment by drcmda** [comment]
Released it today: https://twitter.com/0xca0a/status/1081185260208078849
