### ISSUE TITLE
Page also zooms when using pinch to scale objects using useGesture

### ISSUE THREAD

**Issue by AudunBeck** [react-spring/react-use-gesture#106]
Been trying to get useGesture to work where pinching to scale and rotate won't also zoom the site im currently on, but does not seem to work correctly. 
Am I wrong thinking this should work at all? Even the example provided at https://codesandbox.io/s/9o92o24wrr zooms when pinching to scale the object.

**Comment by dbismut** [comment]
@AudunBeck hey, what's the device you're testing against?

**Comment by AudunBeck** [comment]
@dbismut firefox on desktop and both firefox and chrome on android.

**Comment by dbismut** [comment]
@AudunBeck I've updated the sandbox with `touch-action: none`. Let me know if that works for you!

**Comment by AudunBeck** [comment]
@dbismut  Does not seem like the sandbox have updated yet.

**Comment by dbismut** [comment]
Damn you’re right. I rushed this before a meeting and now I’m stuck. Will update in 30mn or so but touch-action: none in the outer div should make it work.

**Comment by AudunBeck** [comment]
I will check it when i get back infront of a pc again!
________________________________

**Comment by AudunBeck** [comment]
I will look into it when i get infront of a pc again!

**Comment by AudunBeck** [comment]
Seems to be working on my end now!
