### ISSUE TITLE
🔮 v7 now in beta!

### ISSUE THREAD

**Issue by dbismut** [react-spring/react-use-gesture#111]
Following #109, I've started working on v7, which is now available with the beta tag. You can install it like so:
```
yarn add react-use-gesture@beta
```

### 📕 [Docs](https://use-gesture.netlify.com/)

React-use-gesture has a proper [documentation website](https://use-gesture.netlify.com/)!

### ⛱ Sandbox
You can play with v7 options in this sandbox: https://codesandbox.io/s/react-use-gesture-v7-oft72

#### All gestures
- Added `threshold` config option that will prevent the gesture handler to fire if the gesture displacement hasn't breached a threshold.
- Added `elapsedTime` to `state` that will contain the elapsed time of the gesture (from start to end).

#### Coordinates based gestures
- Added a `axis` config option that can accept `'x'` or `'y'` and that will result in the handler only being fired when the gesture is initiated along the specified axis. 
- Added a `lockDirection` config option that when true will lock the gesture movement in the first intentional axis.
- Added bounds `{top, bottom, left, right}`
- Added rubberbanding to simulate gesture elasticity out of bounds

#### useDrag
- Added `threshold` config option that will prevent `useDrag` to fire if the gesture displacement hasn't breached a threshold.
- Added a `filterTaps` config option that will fire the drag handler with the `tap` attribute set to `true` if the user has tapped and released with a displacement inferior to `3`.
- Added a `swipe` state option that will help users identify if the gesture was a `swipeLeft|Right|Top|Bottom`. Swipe recognition can be customized with `swipeVelocity` and `swipeDistance` config options.

### ⏳ Progress
- [x] Support refs
- [x] useWheel
- [x] useScroll
- [x] useMove
- [x] usePinch 😭
- [x] Integrate `onStart` / `onEnd`
- [x] Pass on traditional handlers (`onClick`, `onMouseMove`, etc.)
- [x] Test new features 🤯
- [x] Comment code 😞
- [x] Write new docs

If there's any other features you would like this lib to support, this is the right place!

**Comment by TheHolyWaffle** [comment]
Allow for tree-shaking by marking the library as side-effect free?

See https://bundlephobia.com/result?p=react-use-gesture@7.0.0-alpha.9

**Comment by dbismut** [comment]
Hey @TheHolyWaffle can you please expand on this? I'm not an expert, I know what tree-shakable means, not sure exactly how to mark the library side-effects free? I'm using `rollup` as a bundler, not sure adding `"side-effects": false` to `package.json` would change anything, but again, I'm not sure about what I'm writing 😅

**Comment by TheHolyWaffle** [comment]
@dbismut That's exactly how you would enable it :) Indeed, it seems like there is benefit to it yet. But it might help out in the future some time. I don't see a downside of having it be marked side effect for now.

**Comment by longjinxiang** [comment]
Can I use it in windows？

**Comment by dbismut** [comment]
@longjinxiang what do you mean?

**Comment by Krispy3000** [comment]
Hello, I was testing the bounds and rubberand options and they work great on their own, but don't seem to work with decay. I'm attempting to recreate touch scrolling on iOS. Is this a planned feature or something that I should handle manually with onFrame callbacks?

**Comment by satvikpendem** [comment]
Just posted on an older issue but there seems to be a bug in versions >6 where a drag gesture will continue even after the mouse is off of the draggable element. This does not appear in versions before 6, such as 5.2.4, so it might be something that was changed between then and now. Could see a fix in v7.

https://github.com/react-spring/react-use-gesture/issues/74#issuecomment-567219459

**Comment by dbismut** [comment]
@Krispy3000 I think I know what you mean but unfortunately you'll have to look at react-spring rather than react-use-gesture. React-use-gesture doesn't animate per se, it only fires handlers when an event is fired.

However, I had created some weeks ago an inertia example doing what you want, and I just updated it to benefit from v7 and latest react-spring canary. Have a look!

https://codesandbox.io/s/spring-inertia-latest-oo3mi

**Comment by dbismut** [comment]
**React-use-gesture v7 is now in beta with [new docs](https://use-gesture.netlify.com/)!**

```
yarn add react-use-gesture@beta

npm install --save react-use-gesture@beta
```

**Comment by Krispy3000** [comment]
Great, thank you! The separation of concerns makes sense and I appreciate the code example. You probably already know that it has some erratic behavior and I'd like to help work out a solid code pattern. I'll open a ticket for inertia rubberbanding with react-spring to continue discussion.

The docs are also very helpful. I just wanted to point out there appears to be some missing urls, for example on the [Available Hooks page under Usage](https://use-gesture.netlify.com/docs/hooks).

**Comment by dbismut** [comment]
You’re right, I’ll fix the URLs tomorrow!

**Comment by dbismut** [comment]
@Krispy3000 can you point me to the erratic behavior on the inertia sandbox? I can’t reproduce :)

**Comment by Krispy3000** [comment]
@dbismut I was about to make a video this morning but when I loaded the codesandbox it seems that you have already fixed the bug! Just to be clear, what I was reproducing was giving the block some inertia, then clicking on it (but not dragging) while it was at rest and the it would move with the previous inertia. There would be harder to reproduce issues where the block would fly in the opposite direction I expected, but that also appears to be fixed. Cheers!

**Comment by Krispy3000** [comment]
Okay here are some issues I reproduced that have to do with flicking the box on the bounds a bunch of times: https://www.dropbox.com/s/w5vua952ts57ey1/inertia%20bug.mkv?dl=0

**Comment by dbismut** [comment]
@Krispy3000 I see! I think one of the bug comes from your mouse coming out of the viewport. Maybe that can be fixed in react use gesture directly (ie canceling drag if this happens). I’ve created another sandbox in the meantime that is closer to emulate scrolling. It’s not perfect but let me know if some of the bugs disappear. 

hey about the inertia thing: https://codesandbox.io/s/inertia-fake-scroll-wjz5s

**Comment by Krispy3000** [comment]
@dbismut Thanks, I'm not getting stuck on the bounds anymore (even when I try to force it). I'd say the biggest issue for me right now has to do with inertia and expectations. What I expect to happen is that each swipe builds up inertia (to a reasonable limit) and only a click stops the movement and makes its drag immediate. For example, Flickity works exactly as expected and has an excellent user experience: 
[Codepen](https://codepen.io/desandro/pen/bNLGNZ) | [Video](https://www.dropbox.com/s/sh8jd5qnkdu22ql/flickity%20inertia%20-%20smooth.mkv?dl=0)

However, with the react-spring/gesture example I get something choppy like this: [Video](https://www.dropbox.com/s/2omfoojd9c1lnm1/react-spring%20inertia%20-%20not%20smooth%20.mkv?dl=0)

This might have more to do with the inertia logic than react-use-gesture so I understand if it's a bit off topic here.

**Comment by dbismut** [comment]
That’s ok no worries. It might be on topic if the bug is on the React use gesture side. 

However I’ve just reported a bug on React-spring latest canary which I think has to do with what you’re experiencing:

https://github.com/react-spring/react-spring/issues/887

**Comment by kivervinicius** [comment]
Swipe not works in last beta, demo is broken

**Comment by dbismut** [comment]
@kivervinicius seems to work fine on my iPhone can you please expand and specify OS / browser / hardware your using?

**Comment by kivervinicius** [comment]
Sorry, @dbismut i maked confused here, but demo have a problem on `console` should be `console.log`

**Comment by dbismut** [comment]
@kivervinicius I'm not sure I know which demo you're referring to then.

**Comment by kivervinicius** [comment]
@dbismut https://codesandbox.io/s/react-use-gesture-v7-oft72 
![image](https://user-images.githubusercontent.com/4115328/72352680-178a2300-36b9-11ea-8372-ed03e3705f07.png)

**Comment by impulse** [comment]
First of all thanks for this great new version, I really loved the `bounds` and `rubberband` utilities so I tried making a gallery slider (similar to Instagram) out of it. There is one thing which I would like to see in the documentation because I ran into this while using `axis` / `lockDirection`. Having the animated div wrapped in another container (for example a relative div that contained the animated images, controls and caption) would require all outer containers to have `touchAction: 'none'` in order to have the scroll lock working.

**Comment by dbismut** [comment]
Hey @impulse thanks for the feedback, glad you like it! There’s a `touch-action` section in the docs, did you have a look at it?

Maybe I should point to it in sections dedicated to `axis` and `lockDirection`, is that what you hinted towards?

**Comment by impulse** [comment]
@dbismut oh perfect, wouldn't really have noticed it without your mention. Linking it at `axis` / `lockDirection` or splitting the `Useful extras` page into multiple with more descriptive names should fix that.

**Comment by dbismut** [comment]
Yeah I might as well do that. Actually touch-action is useful whenever dragging something in a scrolling component!

**Comment by impulse** [comment]
I don't know the exact reason why, but touch-action seems to be worse on iOS than Android. Been researching how Instagram does this and they basically have a container with overflow-hidden and `touch-action: pan-y` and some JS to prevent vertical scrolling when swiping through images. The threshold seems to be way lower when starting to drag diagonally on iOS though (doesn't matter which browser). There might be a polyfill to have a better platform support.

**Comment by dbismut** [comment]
Hm can you send me a sandbox so I can test? I know that `touch-action` isn’t perfect on my iPhone but unfortunately I’m not sure there’s a possible alternative. You might have a try at `body-scroll-lock` but I don’t think you can prevent scroll after touchStart...

**Comment by dbismut** [comment]
v7.0.0 is now out!
