### ISSUE TITLE
Add elapsed time

### ISSUE THREAD

**Issue by mrsimb** [react-spring/react-use-gesture#112]
Hello! Thank you again for this wonderful library.

In my case, i have a pannable container with draggable items. I want the drag to actually start if user holds mouse more than 180ms.

I would use config.dragDelay, but i need to catch the first mousedown event, and stop its propagation down to the pannable container, so panning wouldn't start too.

The soultion i have now, is to memoize first timestamp (memo = time) and then calculate elapsed time (elapsed = time - memo) to check if drag should happen.

I think it could be useful to include elapsed time into gesture state to reduce handler code boilerplateness.

**Comment by dbismut** [comment]
Hey @mrsimb thanks for the suggestion! Can you please share a codesandbox with your current workaround? Thanks!

**Comment by mrsimb** [comment]
Okay, will do after i get to home.

**Comment by dbismut** [comment]
Hey @mrsimb did you have time to have a try?

**Comment by drcmda** [comment]
elapsed time would be super useful. i added it to react-three-fiber as well. it's just a

    const now = Date.now()
    const elapsed = (now - last) / 1000
    last = now

**Comment by dbismut** [comment]
`elapsedTime` has been added in `7.0.0-alpha.22`, which currently supports drag and wheel gesture.

**Comment by mrsimb** [comment]
great, thanks!
also sorry, i forgot to reply
