### ISSUE TITLE
If domTarget.current is null at unmount, bind will not return the right cleaning function

### ISSUE THREAD

**Issue by sinoon** [react-spring/react-use-gesture#115]
I need use useGesture with passive false mode, and I use useGesture with function as first argument.

Question 1 : gesture bind seems like not work
Question 2 : binds function return a object not a function for remove listener. 
`Warning: An effect function must not return anything besides a function, which is used for clean-up. You returned: [object Object]`

But a little bit different. Let me show code

first I combined a logic with useLogic, and return some useful value.

```TypeScript
const useLogic = (list: DataRange['range'], ref: React.RefObject<EventTarget>) => {
    const refData = useRef(0)

    const [dateRange, setDateRange] = useSprings(list.length, index => ({
        move: index * 40,
        // TODO
        base: refData.current * 40,
    }))

    const binds = useGesture(
        ({ down, event, delta: [, yDelta] }) => {
            if (event) {
                event.preventDefault()
                event.stopPropagation()
            }

            // calc current position
            if (!down) {
                refData.current += Math.round(yDelta / 40)
                refData.current = clamp(refData.current, -list.length + 1, 0)
            }
            // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
            // @ts-ignore
            setDateRange(index => {
                const move = index * 40 + (down ? yDelta + refData.current * 40 : refData.current * 40)
                const base = refData.current * 40

                return {
                    move,
                    base,
                    immediate: down,
                }
            })
        },
        {
            domTarget: ref,
            event: { passive: false, capture: true },
        },
    )

    useEffect(binds, [binds])

    return [binds, dateRange, refData] as const
}
```

And then, I create a loop for itearot list

```TypeScript
const list: {
        name: DataRange['name']
        range: DataRange['range']
        suffix?: DataRange['suffix']
        binds: UseLogic[0]
        dataRange: UseLogic[1]
        currentRef: UseLogic[2]
        ref: React.RefObject<HTMLDivElement>
    }[] = []
    for (let i = 0; i < dataList.length; i++) {
        const { name, range, suffix } = dataList[i]
        const ref = useRef(null)
        const [binds, dataRange, currentRef] = useLogic(range, ref)

        list.push({
            name,
            binds,
            dataRange,
            currentRef,
            range,
            suffix,
            ref,
        })
    }
```

Finally, render the list

```TSX
{list.map(({ name, dataRange, range, suffix, ref }) => {
        return (
            <animated.div
                key={name}
                className={style.rangeItemContainer}
                ref={ref}
            >
                {dataRange.map(({ base, move }, index) => {
                    return (
                        <animated.div
                            key={index}
                            style={{
                                opacity: move.interpolate({
                                    range: [
                                        -range.length * 40,
                                        base.getValue(),
                                        range.length * 40
                                    ],
                                    output: [0, 1, 0]
                                }),
                                transform: move.interpolate(
                                    move => `translateY(${move}px)`
                                )
                            }}
                            className={style.text}
                        >
                            {range[index]}
                            {suffix}
                        </animated.div>
                    )
                })}
            </animated.div>
        )
    })}
```

**Comment by dbismut** [comment]
Hi @sinoon, using a function as the first argument for `useGesture` to make it default for drag was removed when specific gesture hooks were introduced. You can now use `useDrag` instead!

**Comment by sinoon** [comment]
Thank you , But when i use `useDrag`, i got same error

![image](https://user-images.githubusercontent.com/6065488/69911674-02836880-145a-11ea-81b3-50a879e7b2b1.png)

And more, type error with 
![image](https://user-images.githubusercontent.com/6065488/69911693-1a5aec80-145a-11ea-8d0a-6be66aaf1015.png)

Only thing I change it use `useDrag` instead of `useGesture`

**Comment by dbismut** [comment]
Can you please open a repro on codesandbox?

**Comment by sinoon** [comment]
https://codesandbox.io/s/multi-gesture-card-zfboo?fontsize=14&hidenavigation=1&theme=dark

**Comment by dbismut** [comment]
@sinoon I'll see what I can do but I'm not seeing the error you were referring toN

**Comment by sinoon** [comment]
I don't know why there no error, but is not work when i move the year or month

**Comment by dbismut** [comment]
Here's a quick fix, you were using `delta` instead of `movement`. I assume you were used to v5, v6 labelled things differently.

https://codesandbox.io/s/multi-gesture-card-0jrcy

I'll see if there's a simpler implementation of it, this seems a bit circumvolved.

**Comment by sinoon** [comment]
Yeah, it worked, I am using v5 indeed ! Big Thank for you !

I need investigate more because of my local code doesn't work but demo is fine :( It's seem like without binding event handler.

Is't very interesting, when I set show in initialize, it will ok, but is case of initialize with hide, it will not work, because of the ref.current is null, so the bind will not work.

**Comment by sinoon** [comment]
And If set initialize with hide the component, the error will show

![image](https://user-images.githubusercontent.com/6065488/69916926-e0aad580-149b-11ea-8b54-54caacfc7994.png)

**Comment by dbismut** [comment]
I'll investigate this. In the meantime here is another demo with simpler code I think, which doesn't use refs. The tip here is to use `touch-action: none` to indicate to the browser it shouldn't scroll the viewport when interacting with the menu.

https://codesandbox.io/s/react-use-gesture-template-4vs50

**Comment by dbismut** [comment]
> And If set initialize with hide the component, the error will show

Indeed, this is a valid edge-case bug I think. It should be fixed in v7 though (just released `alpha.29` which fixes it).
