### ISSUE TITLE
filterClicks broken on 7.0.0-alpha.35 and up

### ISSUE THREAD

**Issue by Krispy3000** [react-spring/react-use-gesture#120]
Click returns "undefined" when filterClicks is set to true for 7.0.0-alpha.35 and up, but not 7.0.0-alpha.34.

**Comment by dbismut** [comment]
Yeah sorry I’m changing the api from click to tap and filterClicks to filterTaps. I’m planning to release a beta before Christmas, I’m currently writing a full documentation.
