### ISSUE TITLE
Updating a spring's position from a source other than a gesture

### ISSUE THREAD

**Issue by geofflittle** [react-spring/react-use-gesture#124]
Hello,

I have two sources that update a spring's position, the first being the traditional case, via a gesture, and the second triggered via window resize.  When the resize takes place, I calculate the percent width and height of the spring using the window's previous size, then apply this to the window's current size.

This works when performing a resize--the spring / element moves across the screen as expected--however subsequently performing a drag causes the spring to "reset".  My intuition tells me that this is because the `useDrag` hook / `offset` state is not being updated when the window is resized.  Consequently, the `offset` state "returns" the spring to where it was before the resize (and in terms of pixels, not percents).

As an example,  if the window is 200 pixels wide and my spring is at `x: 50`, when I resize the window to 100 pixels wide, the spring's state is appropriately set to `x: 25`, however when I click on it to drag it, it's returned to `x: 50`.

Here's an example of what I'm doing.

https://codesandbox.io/s/tender-ganguly-no0g7

Is there a way that I can update the `useDrag` hook so that `offset` is calculated correctly after a window resize?  Perhaps this would be a function returned from `useDrag`?  I imagine this would be useful if the spring's state was set from any arbitrary source (not just window resize).

Thanks,
Geoff

**Comment by geofflittle** [comment]
I think I figured out a work-around.  I can use the `values` state provided in the `useDrag` callback.  This is not perfect since when I click the spring / element, it moves under the drag so that its anchor (top left of the div) is directly under the mouse, but this slight movement is better than the seemingly random movements I was seeing before.

**Comment by dbismut** [comment]
Hi @geofflittle, here's your sandbox amended:
https://codesandbox.io/s/holy-cache-nl640

In `<7.0.0`, this was typically a use case for `memo`, but now `7.x` brings `initial` which allows you to set the initial offset for `movement`.

[Read the docs!](https://use-gesture.netlify.com/docs/options#initial)
