### ISSUE TITLE
useSprings DraggableList demo breaks with react-use-gesture v6+

### ISSUE THREAD

**Issue by nnnoel** [react-spring/react-use-gesture#125]
[CodeSandbox](https://codesandbox.io/embed/r5qmj8m6lq) from the react-spring docs.

After toying around with the latest sandbox dependencies, I noticed that the DraggableList demo doesn't work anymore after the release of `react-use-gesture` v6.

**Comment by nnnoel** [comment]
But after stumbling across the demo from use-react-gesture, it appears to work with v7. https://codesandbox.io/s/fh8r8

**Comment by dbismut** [comment]
@nnnoel yes we absolutely do need to have the same sandboxes in the react-spring ecosystem, I understand this is confusion-prone!
