### ISSUE TITLE
elapsedTime of tap events

### ISSUE THREAD

**Issue by zvictor** [react-spring/react-use-gesture#126]
In my application I would like to take some action in case the user performs a quick tap - _a touchStart/mouseDown followed by touchEnd/mouseUp in less than 300ms_.

I took a look at

```js
useDrag(({
    elapsedTime, // gesture elapsed time
    tap,         // is the drag assimilated to a tap
}), { fliterTaps: true })
```

and it works as I expected when the gesture contains a movement, which means that, as long as the user moves the pointer during the tap, `elapsedTime` will be higher than zero when `last === true`. 

However, **in case no movement happens `elapsedTime` remains constantly as zero**.

Is this by design? If so, why?

**Comment by dbismut** [comment]
Hey, @zvictor have you tried the [delay](https://use-gesture.netlify.com/docs/options#delay-drag-only) option?

`filterTaps / tap` is designed to detect taps based on gesture displacement, not on duration (note that this is consistent with how browsers detect clicks / taps).

`delay` won't trigger the gesture until the delay is reached or the mouse is moved.

`elapsedTime` measures the elapsed time of the drag gesture, so until it actually detects a drag `elapsedTime` will remain `0`.

PS: btw just noticed there's a typo on `fLiterTaps` in the docs 🤷‍♂️ Fixing this now.

**Comment by zvictor** [comment]
`delay` is unfortunately not an option because I have multiple actions happening inside the gesture handler (think on Instagram's stories, where you can hold to pause, tap to skip to next or swipe to jump the whole block).

`delay` would remove my ability to handle movements that are based on `first`.

---

I think I understand your point of keeping `elapsedTime` restricted to gesture movements from a "_philosophical_" perspective, but I am still not sure I would agree with it.

If I can just put in my two cents, I think that once we start adding support to things like `tap` and `filterTaps` we are not only about gestures anymore. Therefore, we should consider giving support as appropriated as possible to those features.

Do you also see any practical disadvantage if we switch to a "_calculate `elapsedTime` on tap_" mode?

**Comment by dbismut** [comment]
No that’s ok, I’ll make the change and release it shortly!

**Comment by zvictor** [comment]
I just tested with `7.0.0-beta.8` and it worked fine. Thank you so much! 🎉

**Comment by dbismut** [comment]
Hey @zvictor i published the version too fast (I though I unpublished it though!). I’ve made some other adjustments and there were some side effects. I’ll let you know once beta 9 is out.

**Comment by dbismut** [comment]
@zvictor `beta.9` should fix it correctly. I was trying to switch to pointer events by default thinking it would be a good idea but it's actually really complex. I'll work on this separately.

Let me know if you encounter any issues!
