### ISSUE TITLE
left mouse click doesn't drag

### ISSUE THREAD

**Issue by zcaalock** [react-spring/react-use-gesture#128]
any idea why right click drag works and left doesn't?

![drag](https://user-images.githubusercontent.com/24411061/71767103-b15b0e80-2f08-11ea-9ffb-5d6f7e448eac.gif)

**Comment by dbismut** [comment]
Can you please link to the sandbox + OS and browser version?

**Comment by zcaalock** [comment]
https://codesandbox.io/s/viewpager-xcg52
