### ISSUE TITLE
initial value

### ISSUE THREAD

**Issue by zcaalock** [react-spring/react-use-gesture#129]
is there way to set initial value of which photo will be visible at start (fe. third one)?

i want to store id of current photo and when coming back to the gallery be able to see this photo on top

https://codesandbox.io/s/viewpager-xcg52

**Comment by dbismut** [comment]
@zcaalock I'm not sure how this is related to how the lib functions, it's really something you should ask on Spectrum. In your situation, you should look at setting the initial spring with the value allowing the photo you want to be shown to be at the correct position.

``` jsx
  const [props, set] = useSprings(pages.length, i => ({
    x: i * window.innerWidth - 500, // <-- look at this value
    scale: 1,
    display: 'box', // <-- set style directly, doesn't need to be interpolated through springs
    opacity: '1', // <-- this should be a number, not a string,
    userSelect: 'none' // <-- set style directly, doesn't need to be interpolated through springs
  }))
```

**Comment by zcaalock** [comment]
thanks, this works exactly as i want

**Comment by zcaalock** [comment]
here is the resolve

`const index = useRef(counter)
  const [props, set] = useSprings(pages.length, i => ({
    x: (i - index.current) * window.innerWidth,       
    scale: 1,
    display: 'box',
    opacity: 1,
    userSelect: 'none'
  }))`

**Comment by dbismut** [comment]
Glad you figured it out. Once more though, display and userSelect shouldn’t be in your spring logic unless you actually change them. Just pass them as regular style attributes in the style prop of your component.
