### ISSUE TITLE
Drag and inertia

### ISSUE THREAD

**Issue by Spy-Seth** [react-spring/react-use-gesture#132]
Hi! 

First I want to congrats you guys for this wonderful library!

I'm implementing a drag interaction that require to continue after that the user end the drag: aka inertia. After looking the documentation it seems the library manage already the velocity but did not allow to continue the mouvement after the user release the draggable element. 

Did you have any plan to implement something to handle it?

**Comment by dbismut** [comment]
Hi @Spy-Seth thanks for the kind words.
I think it should rather be part of react-spring rather than react-use-gesture. I made a sandbox a few weeks ago trying to replicate inertia. You can find it right there:

https://codesandbox.io/s/inertia-fake-scroll-wjz5s

It also supports wheel, but it's not perfect on that aspect. Let me know if this helps!

**Comment by Spy-Seth** [comment]
Ho I didn't know the `useGesture` callback could be trigger after that the movement end. And I'm not sure to understand yet why it get trigger again 😅 

> https://codesandbox.io/s/inertia-fake-scroll-wjz5s

This example is perfect thanks! 😄 

> I think it should rather be part of react-spring rather than react-use-gesture.

The inertia concept is really link to user movement and it could be also natural to have helper to manage it in this package

**Comment by dbismut** [comment]
> Ho I didn't know the useGesture callback could be trigger after that the movement end. And I'm not sure to understand yet why it get trigger again

Not sure what you mean there sorry, can you elaborate?

> The inertia concept is really link to user movement and it could be also natural to have helper to manage it in this package.

Valid point, but again, react-use-gesture only gives you the initial velocity and direction of the movement. What you do with it, how you animate your component depending on these two variables is up to the user and the animation library. React-use-gesture will never animate anything: it only gives you data about events.
