### ISSUE TITLE
useHover is not a function

### ISSUE THREAD

**Issue by ericaolliges** [react-spring/react-use-gesture#135]
I can't find mention of this on the site, but on upgrading to v7.0.0 useHover seems to have been removed and is now returning an Object(...) is not a function error. Is there any relevant changelog for this?

**Comment by ClayCooperLA** [comment]
I came here to ask about this as well. I was playing with this example here: [https://codesandbox.io/s/react-three-fiber-gestures-v8nlo](https://codesandbox.io/s/react-three-fiber-gestures-v8nlo)
I noticed that if I upgrade `react-use-gesture` to `v7.0.0` there is a `useHover is not a function error`. So I removed the `useHover` stuff and now I see the gesture is not binding to the mesh at all 😢. This is coolest stuff ever guys, v6.0.14 works for now 🙇

**Comment by ericaolliges** [comment]
From what I can tell this still works in the useGesture block, so I had to rewrite it like this:
`useGesture({
    onHover: () => {/* do stuff */}
 });`

**Comment by dbismut** [comment]
Damn if that’s true I’m so so sorry guys. The tests only test useGesture, not specific hooks. I’ll fix this ASAP. Sorry for this again.

**Comment by dbismut** [comment]
Hi @ericaolliges @ClayCooperLA this should be now fixed in `7.0.1`. Hopefully this works out for you! Sorry again about this 🤦‍♂️

**Comment by ClayCooperLA** [comment]
@dbismut thank you so much for your quick response! I don't want to jump to conclusions, perhaps I am implementing incorrectly. However, I am not experiencing any difference with `v7.0.1`. I am unable to get any values when using `{...bind()}` on a `<a.mesh />` object. The example sandbox has the same issue. 🙇

**Comment by dbismut** [comment]
Hey @ClayCooperLA I’m on my phone atm but I’ve looked at the sandbox code. The API has slightly changed with v7 and to activate pointers you actually need to pass `{ eventOptions: { pointer: true } }` instead of `{ pointerEvents: true }`. Hope this helps!

**Comment by ClayCooperLA** [comment]
@dbismut That was it! You're a legend. Thank you!
