### ISSUE TITLE
Is it possible to use drag inside of an iframe?

### ISSUE THREAD

**Issue by ben-styling** [react-spring/react-use-gesture#137]
I'd like to be able to use drag inside of an iframe. I don't need to drag in or out of it, just inside is fine.

It looks like it knows when it's been clicked, but doesn't know the mouse is moving afterwards.

Here's an example: https://codesandbox.io/s/use-gesture-inside-of-iframe-q8s6e

**Comment by dbismut** [comment]
Im not in front of a computer but I understand why this might fail. Try using the pointer or window option see this https://github.com/react-spring/react-use-gesture/pull/48

**Comment by ben-styling** [comment]
Sorry, I must have missed that option!

Supplying the window option works perfectly. Thank you!

Updated sandbox for reference: https://codesandbox.io/s/use-gesture-inside-of-iframe-1qowo
