### ISSUE TITLE
Make useDrag / onDrag compatible with Microsoft Surface

### ISSUE THREAD

**Issue by impulse** [react-spring/react-use-gesture#138]
Seems not to be working on Surface devices (tested on Surface Pro 6 and Surface Studio 2). Events only seem to fire when using onTouchMove.

**Comment by dbismut** [comment]
Hi @impulse thanks for reporting the issue.

Can you please make sure you're using the latest version (some of the sandbox examples might not be updated)? This seems to be related to #136 (unfortunately I can hardly test this on my side).

Can you please check if passing the following option : `{ events: { pointer: true } }` changes anything?

**Comment by impulse** [comment]
Oh nice, I was still on `7.0.2` but `7.0.4` fixes the issue (passing the option is not needed).

By the way I did not forget about this https://github.com/react-spring/react-use-gesture/issues/111#issuecomment-575328821, just didn't have the time for it yet (hopefully this week).

Thanks!

**Comment by dbismut** [comment]
😅 sure let me know when you can, no pressure!
