### ISSUE TITLE
Set axis = 'x' results in Cannot read property 'map' of undefined for useWheel

### ISSUE THREAD

**Issue by arelaxend** [react-spring/react-use-gesture#140]
Dear contributors,

**Version**
7.0.4

**Steps to reproduce**
Set option axis = 'x' and use "useWheel"

it throws the following exception:
```
TypeError
Cannot read property 'map' of undefined
calculateDirection
https://xxx.csb.app/node_modules/react-use-gesture/dist/react-use-gesture.cjs.development.js:63:16
WheelRecognizer._this.onWheelStart
https://xxx.csb.app/node_modules/react-use-gesture/dist/react-use-gesture.cjs.development.js:1961:20
```

**What is the expected result**
It should scroll in the x direction

Best, A.

**Comment by dbismut** [comment]
Hi @arelaxend thanks for reporting the issue, more complex than I thought to debug but should be fixed in `7.0.5`. Let me know how it goes :)
