### ISSUE TITLE
load dynamic data with useGesture?

### ISSUE THREAD

**Issue by pennjlin** [react-spring/react-use-gesture#141]
Hi there, I'm new to React hooks and am trying to use `react-springs` in conjunction with `react-use-gesture` to render some swipe animations on a deck of cards. However I noticed all the examples online are using hardcoded data. If I wanted to fetch data asynchronously, I'd be prompted an error when calling `useSprings` and `useGesture` in `useEffect()` because (custom) hooks cannot be called in another hook or callback and have to be called in the top level of React function component. I was able to get around this for `useSprings()` with the fix suggested [here](https://spectrum.chat/react-spring/general/provide-dynamically-loaded-value-to-usespring~bb6dc611-c62a-4615-8dae-5d253fc252c0), but it had no mention of `useGesture` so I'm kind of stuck. 

```
function Deck() { 

  var [cardData, setCardData] = useState([]);
  const [props, set] = useSprings( cardData.length, i => ({...to(i), from: from(i)}) );
  const [gone] = useState(() => new Set());

  // asynchronously fetch data 
  useEffect(() => {
    async function fetchData() {
      let resp = await axios.get(DATABASE_URL), {
        headers: {
          'Content-Type': 'application/json',
        }
      });
      setCardData(resp.data);
    }
    fetchData();
  }, []);

  // dynamically update useSprings()
  useEffect(() => {
    set( cardData.length, i => ({...to(i), from: from(i)}) );
  }, [cardData]);

  // how to trigger reload on data fetch? 
  const bind = useGesture(
  ({
    args: [index],
    down,
    delta: [xDelta],
    distance,
    direction: [xDir],
    velocity
  }) => {
    const trigger = velocity > 0.2;
    const dir = xDir < 0 ? -1 : 1;
    if (!down && trigger) gone.add(index);

    set(i => {
      if (index !== i) return;
      const isGone = gone.has(index);
      const x = isGone ? (200 + window.innerWidth) * dir : down ? xDelta : 0;
      const rot = xDelta / 100 + (isGone ? dir * 10 * velocity : 0);
      const scale = down ? 1.1 : 1;

      return {
        x,
        rot,
        scale,
        delay: undefined,
        config: { friction: 50, tension: down ? 800 : isGone ? 200 : 500 }
      };
    });

    if (!down && gone.size === cardData.length)
      setTimeout(() => gone.clear() || set(i => to(i)), 600);
  }, [props, cardData]);
  /* end of useGesture() */

  return props.map(({ x, y, rot, scale }, i) => (
    <Card
      className={classes.stackedCards}
      i={i}
      x={x}
      y={y}
      rot={rot}
      scale={scale}
      trans={trans}
      data={cardData}
      bind={bind}
    />
  ))

}
```

Specifically, I can now dynamically reload `props` and `data` from useSprings upon data fetch, but am unable to reload `useGesture` with some sort of trigger in mind. Has anyone ran into a similar issue or come up with a workaround? Thanks so much for helping!

**Comment by dbismut** [comment]
You shouldn’t need to reload useGesture. Please note that you’re probably using an old version of react-use-gesture based on what I understand form your code.

**Comment by pennjlin** [comment]
How should I be approaching the dynamic reload then? You're correct that I was using `react-with-gesture` previously. Now that I updated it to latest `react-use-gesture`, the same issue persists. What'd be the correct way to support async/await data fetching with `react-springs`?

**Comment by jaxball** [comment]
@dbismut

**Comment by dbismut** [comment]
Are you able to package a codesandbox example so that I can have a look? There’s no reason why you should need to « reload » useGesture.

**Comment by pennjlin** [comment]
> You shouldn’t need to reload useGesture. Please note that you’re probably using an old version of react-use-gesture based on what I understand form your code.

Thanks @dbismut! This is resolved. some earlier examples of card swipe that imported `react-with-gesture` called `useGesture()` the way you would with `useDrag()` in `react-use-gesture`. Perhaps it'd be helpful for the maintainers to put a comment in the API dos that the deprecated `useGesture` took incompatible arguments.

**Comment by dbismut** [comment]
I’ll consider this.
