### ISSUE TITLE
How can I execute useDrag after calculating the height of elements?

### ISSUE THREAD

**Issue by moonketo** [react-spring/react-use-gesture#143]
my goal is to reflect the height of the elements in the bounds value of the config. (after first rendering)
the elements can be asynchronous or static files.

**Comment by dbismut** [comment]
Hey. I'm usually very open to helping people but please make the minimum effort of properly explaining your problem, attempts, sending a codesandbox link so I can understand what you mean. I'm closing as this is a question, and I'm not even sure if your question is _how do I measure the bounds of an element?_ (unrelated to this package) or _how do I pass the calculated bounds to `useDrag`?_, in which case you just need to set your bounds as a state variable.
