### ISSUE TITLE
event.stopPropagation() warning.

### ISSUE THREAD

**Issue by ilbrigz** [react-spring/react-use-gesture#146]
Hi! I want the event to not propagate on a container div. So this is what I did.

```
 const outer = useWheel(state => console.log(state))
 const inner = useWheel(
    ({ event }) => {
      event.stopPropagation()
      console.log(event)
    }
  )
return(
<div {...outer()} className="largeOuterDiv">
  <div {...inner()} className="smallInnerDiv"> </div>
</div>
)
```

But I am getting this warning:
This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `stopPropagation` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist()

What could be a fix to this?

**Comment by dbismut** [comment]
This is not specific to this lib, but rather to how React handles events. You need to use the `domTarget` option as explained in the docs FAQ. https://use-gesture.netlify.com/docs/faq#why-am-i-getting-warnings-from-preventdefault-after-i-pass-passivefalse
