### ISSUE TITLE
Outdated and broken spring useGesture examples in React Spring docs

### ISSUE THREAD

**Issue by jmadelaine** [react-spring/react-use-gesture#147]
So I've spent my entire morning trying to replicate [this re-orderable list example](https://codesandbox.io/embed/r5qmj8m6lq) which is featured directly on the [React spring site](https://www.react-spring.io/docs/hooks/examples).

I tried several times to get it working but my list items just weren't dragging more than one or two pixels - and kept resetting their position.

After working on this for some time, I found that the example posted above is extremely outdated, using v5.0.0 of react-use-gesture, and the `delta` value coming from gesture state works in a completely different way to the current version (and even to that of versions 6.x.x).

in version 5, `delta` gives the total distance moved, whereas in versions >= 6, `delta` is the distance moved since the last move.

The examples need to be updated on the React spring website. What is the point of providing an example of code if the code now works in a completely different way?

**Comment by dbismut** [comment]
@aleclarson @drcmda 🤷‍♂️

**Comment by jmadelaine** [comment]
I apologise for demanding that the examples need to be updated - I was very frustrated after being stuck on the same problem for hours.

I've created an [updated CodeSandbox](https://codesandbox.io/s/laughing-shtern-zc9rz) for the example I posted above, that uses react-use-gesture v7.0.6 and `useDrag` instead of `useGesture`.

Would it be possible to update the example featured on the react-spring website? And do you need help with the other examples?

**Comment by dbismut** [comment]
Well, the examples are already updated on this repo. Take a look at the Readme page.

**Comment by stacklikemind** [comment]
I run into the same rabbit hole. Lessons learnt, if there are examples in a git repo, always refer to those.

**Comment by dbismut** [comment]
This will soon be resolved I promise. We will do a cleanup in all examples and normalize everything.
