### ISSUE TITLE
`onPinchEnd` fired twice when pinching out

### ISSUE THREAD

**Issue by tommedema** [react-spring/react-use-gesture#148]
Expected behavior: when I pinch out and release, `onPinchEnd` is fired once

Actual behavior: when I pinch out and release, `onPinchEnd` is fired twice:

<img width="362" alt="Screen Shot 2020-03-27 at 7 54 45 PM" src="https://user-images.githubusercontent.com/331833/77813304-d3c27b00-7064-11ea-8808-fbe8f0c477fc.png">

My code:

```typescript
const onPinchEnd = useCallback((state) => {
    console.log('onPinchEnd')
    console.log(JSON.parse(JSON.stringify(state)))
  }, [])

  const bindPinchGesture = useGesture({ onPinchEnd }, {
    domTarget: canvasContainerRef
  })
```

And in my render function:

```jsx
      <CanvasContainer
        ref={canvasContainerRef}
        className="editor-canvas-container"
        {...bindPinchGesture()}
      >
```

react-use-gesture version: 7.0.5

browser: Safari 13

operating system: iOS 13.3

device: iPhone XS Max

**Comment by dbismut** [comment]
Hi @tommedema thanks for reporting the issue. Would it be possible to set up a sandbox?

**Comment by tommedema** [comment]
@dbismut I've been trying to do so the whole evening... but cannot even get it to log on pinch.

This is where I am now:
https://codesandbox.io/s/elegant-perlman-cdyhi

Open the result page in a new window, enable dev tools and mobile device mode, then use command/ctrl + shift to emulate a pinch event, or open the url on your mobile phone and try to pinch. It's not giving an alert or log statement for me.

**Comment by tommedema** [comment]
@dbismut until we can get the sandbox to work I've created a video of my codebase and a demonstration of the issue here: https://app.usebubbles.com/02d6b5ec-8946-48ab-98c9-56a5b7e7bd42

as you can see it is worse than it just firing a second time, it actually fires every time you do a pointer down or click, after one pinch gesture has been made

**Comment by dbismut** [comment]
Thanks for detailing the issue. Well actually I could have spotted the error from the code in you first message, I missed it sorry. 

The problem is that you’re not using the library correctly using refs. When you use a ref, you shouldn’t spread the bind object onto a component, but rather:

```
React.useEffect(bind, [bind])
```

This is detailed in the docs. I’m not sure why you need to use a ref in your case. 

Also, at this point there’s no real point in using useCallback for handlers, they will recompute in every render.

**Comment by tommedema** [comment]
@dbismut I thought that was it too earlier today but already changed the code and the behavior is exactly the same:

```typescript
  const bindPinchGesture = useGesture({ onPinchEnd }, { domTarget, enabled, eventOptions: { passive: false } })

  // See https://codesandbox.io/s/9o92o24wrr
  useEffect(bindPinchGesture as EffectCallback, [bindPinchGesture])
```

I tripple checked and made sure that the original binding was removed from the element and the behavior has not changed. For every click after the first pinchEnd, it keeps re-firing.

**Comment by dbismut** [comment]
Tom, can you please update your sandbox then? I've made the test with Chrome on MacOS and everything seems to work normally.

https://9r49j.csb.app/
https://codesandbox.io/s/nifty-http-9r49j

**Comment by tommedema** [comment]
@dbismut you've done it for me :) your codesandbox has the bug, I made a video of it:

https://app.usebubbles.com/d5c3a0df-ad3f-4cd2-9780-b4c553d050ac

**Comment by tommedema** [comment]
@dbismut here's real life proof on how this is bugged on Android Chrome:

Video: https://drive.google.com/file/d/166_Je_o3AU5rady_V8pbnSZZPpblb6nI/view?usp=sharing

Sandbox: https://codesandbox.io/s/elegant-perlman-cdyhi

Device: whatsmybrowser.org/b/6XIM2

**Comment by dbismut** [comment]
Hahaha, thanks so much for the details captured, I didn't know about use bubbles, looks like something I will use professionally!

I've just released `7.0.6`, can you let me know if this fixes it for you?

**Comment by dbismut** [comment]
Btw, doesn't seem like Chrome emulating two fingers touch works for me though!

**Comment by tommedema** [comment]
@dbismut beautiful, glad we got this resolved quickly. Also appreciate that you added a unit test.

Glad to see Bubbles being useful to you. Feel free to send any feedback you may have to tom@usebubbles.com.

Re Chrome emulating pinch / two fingers touch: it should work, make sure you hold shift or command or ctrl while scrolling (depends on your operating system I believe).

**Comment by dbismut** [comment]
Wow didn't know you were the author, congratulations. Per Chrome emulation: oh ok, you're talking about control + wheel, which is a way to emulating zooming with a pointer (ie not pinching since there's no angle). This works out of the box, no need to enter responsive mode :)
