### ISSUE TITLE
Question: Dragging whilst scrolling

### ISSUE THREAD

**Issue by Geeman201** [react-spring/react-use-gesture#151]
Hey,

Thanks for open sourcing this library!

I have a question probably best explained with an image.

![scrolling-question](https://user-images.githubusercontent.com/1285296/78452243-19450080-7682-11ea-958e-d95adef740d1.png)

* I have a container with height greater than that of the window. It is scrollable.
* Within that container elements are elements absolutely positioned at a given distance from the top. 
  > In my case this distance is based upon time. The container represents a 24 hour period and events are positioned at the given time.
* When a user drags the yellow item the `top` position is updated and then on the `last` update the time is updated + saved. 

This works fine whilst the user drags within the window, but as soon as the scroll kicks in the numbers start resetting (I believe because `y` is relative to the window rather than my container). I was wandering if there was a way to resolve this?

This basic sandbox demonstrates my problem - drag the grey container till the window scrolls and then observe the funkiness. 
https://codesandbox.io/s/funny-tereshkova-y1e3w 

Thanks in advance!

**Comment by dbismut** [comment]
Hey, I'm not sure I understand what's wrong with your sandbox. There's no reason why the window would scroll (unless you want to address a mobile-specific problem).

Btw `y` is not relative to the window nor the container, it is relative to the origin of the gesture.

**Comment by Geeman201** [comment]
Thanks for the prompt reply.. I think this may be my misunderstanding.. 

In this gif I was expecting `y` to include the distance that was scrolled.

![example](https://user-images.githubusercontent.com/1285296/78458384-bca90c00-76a8-11ea-8d06-6c2d2bea92d8.gif)

**Comment by dbismut** [comment]
Ok what you’re experimenting here is user selection. This shouldn’t happen like this outside of codesandbox preview window but it might be something you’d want to avoid anyway.

Have a look at this sandbox and let me know if it helps. 

https://codesandbox.io/s/epic-feistel-z93vm

**Comment by Geeman201** [comment]
Ahh Perfect!

That makes sense - Thanks! Adding `user-select: none;` whilst draggins fixes my problem 👍

**Comment by dbismut** [comment]
@Geeman201 just in case you're using the code in the sandbox I sent, there's actually a cleaner way to toggle classes using native javascript using `toggle` which accepts a `force` optional secondary argument:

```jsx
document.body.classList.toggle('dragged', down)
```

[See the docs here](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle).
