### ISSUE TITLE
Jest testing mousemove events, translate3d with @testing-library/react

### ISSUE THREAD

**Issue by mayteio** [react-spring/react-use-gesture#154]
I'm creating a Material UI Bottom sheet that works like google maps when you tap on a pin and location information is revealed.

I am having trouble testing the mousedown/mousemove/mouseup events though. I have trawled through the [Drag.test.tsx](https://github.com/react-spring/react-use-gesture/blob/master/test/Drag.test.tsx) to try to understand how it is being tested officially but I just can't get it to work.

[Here's a codesandbox](https://codesandbox.io/s/testing-mouse-events-kn80v?file=/src/BottomSheet.spec.tsx) where you can drag the box vertically in the preview:

Within the test though, translate3d never updates. I've tried copying the official example line for line and am just unsure on why it's not doing anything.

Can anybody shed some light on this?

Here's my very simplified component: 
```js
export const BottomSheet: React.FC<BottomSheetProps> = props => {
  /** Track animateable styles */
  const [{ y }, set] = useSpring(() => ({
    y: 0
  }));

  /** Handle draging */
  const bind = useDrag(
    ({ movement: [, my] }) => {
      set({ y: my });
    },
    {
      initial: () => [0, y.getValue()]
    }
  );

  return (
    <animated.div
      {...bind()}
      style={{ y, backgroundColor: "#eee", width: 100, height: 40 }}
    />
  );
};
```

Here's the relevant test:
```js
test("should move on drag", () => {
    // fire down event on element
    const down = createEvent.mouseDown(element, {
      clientX: 10,
      clientY: 20,
      buttons: 1
    });
    fireEvent(element, down);

    // fire move event on window (doesn't work on el either)
    const move = createEvent.mouseMove(window, {
      clientX: 10,
      clientY: 120,
      buttons: 1
    });
    fireEvent(window, move);

    // FAIL!
    expect(element).toHaveStyle(`
    transform: translate3d(0, 100px, 0
    `);
  });
```
Versions in use:
```
    "@testing-library/jest-dom": "5.3.0",
    "@testing-library/react": "10.0.2",
    "jest-environment-jsdom-sixteen": "1.0.3",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.0",
    "react-spring": "9.0.0-beta.34",
    "react-use-gesture": "7.0.11"
```

**Comment by dbismut** [comment]
Hey @mayteio I'll try to have a look, although I have a ***load of work today. 

I remember spending quite some time working on testing and it has been pretty nerve breaking to make it function correctly. Note that I'm using `test-library@9.x`, I'm having issue with v10 for a reason that I didn't have time to investigate.

Anyway will let you know, please report if you've made progress in the meantime.

**Comment by dbismut** [comment]
Oh right, there's a big difference in the sense that I'm not actually transforming the element in my tests, I'm just passing the values in raw HTML. Also you're not waiting for the spring animation to end so that makes sense why you're getting no change in style.

**Comment by mayteio** [comment]
Thanks @dbismut for the quick response! So you're saying, firstly downgrade to testing-library 9 and making it async. Would I just be waiting for the expect to come back as correct? i.e.

```
async () => {
   ...
   await waitFor(() => expect(el).toHaveStyle(``))
}
```
or is there a way I can know when the spring has finished?

**Comment by dbismut** [comment]
Tbh I just tried running it myself during breakfast and failed to get it working, but yes that’s the general direction I guess. 

No there’s no way to know when the spring has finished from the testing library. The testing library will poll at 50ms for 1000ms (if I remember the docs correctly) until it sees the right value at one point. That’s good enough but you need to be careful with long animations, especially as spring can take a long time to rest.
