### ISSUE TITLE
useDrag's down property is always false in tests

### ISSUE THREAD

**Issue by Noor0** [react-spring/react-use-gesture#155]
I am using `useDrag` to move a component and execute a function if it's dragged by a certain amount but in my tests when I fire `mousedown`, `mousemove` and 'mouseup' the down property is always false.

I'm using `jest` and `react-testing-library`, i know jest uses jsdom and that it doesn't have layout but shouldn't the down property be true on firing a mousedown event?

**Comment by dbismut** [comment]
Can you paste the snippet of your test? down is set to true if the buttons property is set to 1. Have a look at this lib test files.

**Comment by Noor0** [comment]
oh, my bad, i was just using `fireEvent.mouseDown`, guess i'll have to look deeper into the events interface. Thanks for helping.

**Comment by dbismut** [comment]
No worries. It’s just a matter of passing `{ buttons: 1 }` to the `mouseDown` function. Hope it works out!
