### ISSUE TITLE
Once dragged outside window, the next drag is not working.

### ISSUE THREAD

**Issue by mmmmmmmmn** [react-spring/react-use-gesture#156]
I have a problem when I am trying to use react-use-gesture in next.js app.
Once dragged outside window, the next drag is not working.

I guess onMouseUp event does not fire after dropping outside window.

For detail, could you see movie bellow.
![Kapture 2020-04-09 at 21 01 51](https://user-images.githubusercontent.com/51997429/78893008-6b808a00-7aa5-11ea-9d68-5f0305af3b80.gif)

The code is here.
https://codesandbox.io/s/github/mmmmmmmmn/useGestureTest?file=/pages/index.tsx

Is there anything wrong with me?
Could you give some advice.

**Comment by dbismut** [comment]
Hey, so this is a common situation, which I think has to do with `user-select` (the little planet next to your cursor indicates that the browser thinks you're trying to drag and drop something somewhere). To make sure this isn't happening, you may want to add `user-select: none` to your body when you start dragging like in the example below:

https://codesandbox.io/s/epic-feistel-z93vm

Hope it helps.

**Comment by mmmmmmmmn** [comment]
It is a very good idea to add `user-select: none;` style only while dragging.

Your comment is very helpful.
Thank you for your comment!
