### ISSUE TITLE
Handlers in useGesture appear to have different TypeScript signatures

### ISSUE THREAD

**Issue by durad** [react-spring/react-use-gesture#157]
Hi, and thanks for this amazing library!

Consider following code in TypeScript:
``` typescript
  const bind = useGesture({
    onDrag: (e) => {}
  });
```

It compiles nicely and when I hover over `e` in VSCode it says that it is of type `FullGestureState<"drag">`.

However if I change `onDrag` to `onDragStart` like:
``` typescript
  const bind = useGesture({
    onDragStart: (e) => {}
  });
```

I get an error:
```
Parameter 'e' implicitly has an 'any' type.  TS7006

    18 | 
    19 |   const bind = useGesture({
  > 20 |     onDragStart: (e) => {}
       |                   ^
    21 |   });
    22 | 
    23 | 
```

I know I can allow implicit any in tsconfig or set its type explicitly, but it would be nice if the type of the state would be inferred like in `onDrag` case.

**Comment by dbismut** [comment]
You're absolutely right. This is now fixed in `7.0.12`. Thanks for reporting the issue. I'll let you close it if you will!

**Comment by durad** [comment]
Yup, it's working now! I'll close the issue. Thank you!

**Comment by jtaccinelli** [comment]
@dbismut 

Hey - this is an issue that seems to have made a comeback :(

![image](https://user-images.githubusercontent.com/69351250/193159624-027f5747-c790-411d-991f-947704c44e84.png)

is it possible to have this looked into again?

**Comment by dbismut** [comment]
Hey @jtaccinelli what is the version of use gesture you're using and what version of typescript?
