### ISSUE TITLE
Using Arrow Keys to Simulate Swipe Left / Swipe Right

### ISSUE THREAD

**Issue by hariria** [react-spring/react-use-gesture#165]
Hi,

Thanks again so much for your work on this. It's truly incredible, keep it up! I'm using `useGesture` for a project and wanted to use arrow keys (ie. left and right arrow key) to simulate a "swipe left" or "swipe right" on the computer, since swiping is a lot easier on mobile devices than it is on a desktop. How would you recommend I do something like this? Are there functions that can "simulate" a swipe?

Best,
Andrew

**Comment by dbismut** [comment]
Hey Andrew, thanks for the comments, that means a lot.

As you probably know, this lib doesn’t handle keyboards events. That being said you shouldn’t think about how to emulate swipe but rather execute the action that you associate with the swipe when a key is pressed. 

If you have a sandbox of what you’re trying to achieve I can probably help.

**Comment by hariria** [comment]
Thanks for the quick response! I was messing around with your example: https://codesandbox.io/embed/j0y0vpz59. You use `useGesture` in the example to measure a flick (ie. a user has to flick the card with a certain amount of velocity in the right direction in order for it to leave the stack). If there was a way to, for example, flick the cards out on left / right arrow key, that would essentially achieve my goal. Thank you in advance!

**Comment by dbismut** [comment]
Here it is quickly: there's a way to refactor all this to avoid code repetition but you should get the gist ;) https://codesandbox.io/s/cards-2gxc4?file=/src/index.js

**Comment by hariria** [comment]
Awesome! Thank you so much! This is very helpful, really appreciate it!
