### ISSUE TITLE
`useDrag` breaks on mobile with fullscreen

### ISSUE THREAD

**Issue by simon-milleto** [react-spring/react-use-gesture#166]
This issue must be related to the issue #163 but in my case I discovered the issue because of the fullscreen. When the mobile enter in fullscreen mode it no longer responds, here is a minimal example : https://codesandbox.io/s/react-use-gesture-simple-zyi91?file=/src/index.js

The issue appears also on desktop if the chrome devtools is open with responsive mode
Steps to reproduce : 
- Open the link and try to pull up and down on "Pull here", this should work
- Open devtools with responsive mode without reloading
- Try again to pull up and down, this should not work

After some investigations, I noticed that the event `touchstart` is sent but not the `touchmove` and `touchend`, as if the gesture was canceled

PS: After some other tests on the minimal example, even without the fullscreen mode on mobile the `useDrag` breaks and sometimes it worked on desktop with the devtools opened.
Device tested : GalaxyS7 and iPhone 11

**Comment by dbismut** [comment]
Hey, I'm sorry but the repro code is pretty complex, and I don't have time to have a deep look at it at the moment. Would be great if you could simplify it and remove your debugging logs.

#153 deals with react-three-fiber and pointer events management, so it's actually unrelated.

Have a look at this example: https://codesandbox.io/s/action-sheet-zuwji which I believe implements a similar logic. I've tested it on Chrome devtools and my iPhone 11, and it works nicely.

Sorry I can't help more at this point.

**Comment by dbismut** [comment]
I’m closing this as I’m not sure how to reproduce the issue. Feel free to reopen it when you have a sandbox that shows the bug.
