### ISSUE TITLE
useDrag initial: x.get is not a function in Gatsby component

### ISSUE THREAD

**Issue by daninko** [react-spring/react-use-gesture#167]
In learning how to use this library, I pasted the example used for `initial` into a component for a Gatsby build, but get the following error when I click/drag on the rendered element: `TypeError: x.get is not a function`

I'm sure there's something fundamental that I'm missing when porting a vanilla react component to a Gatsby component, but I'm currently stumped as my searches to help me understand where the problem lies.

**Comment by dbismut** [comment]
Hi, which version of reach spring are you using? https://use-gesture.netlify.app/docs/introduction#simple-example

**Comment by daninko** [comment]
^9.0.0-beta.34

**Comment by daninko** [comment]
Upgraded to `^9.0.0-canary.808.17.55c5691` and the error seems to have resolved.

**Comment by dbismut** [comment]
Indeed. I think beta 34 still used getValue instead of get.
