### ISSUE TITLE
Nested component unmounts during drag

### ISSUE THREAD

**Issue by atifsyedali** [react-spring/react-use-gesture#168]
First -> Thank you for this library!

1. I have a nested set of components that are all draggable using a drag handle div.

2. When a component is being dragged, a new ghost image is additionally rendered to that component, and the ghost component is translated to mouse coordinates.

3. When any set of those components are dragged over others in the hierarchy, a feedback is shown on the component. The feedback is maintained through each component's own local state. Each component detects a mouse over event to show visual drag feedback while a global drag flag is set to true.

4. It turns out that dragging children to their parents can cause the parents to redraw the children completely -- which means unmount the children and create new components. 

5. When this does happen, the child that was being dragged is unmounted and the drag ends prematurely and the ghost component disappears.

How do you prevent this kind of situation? I was thinking of making an overlay to put the ghost component in, but that doesn't really solve the problem because the useGesture hook is still cleaned up. Neither can I put the domTarget as something else in the DOM because the drag handle is in each component.

**Comment by dbismut** [comment]
Hi @atifsyedali thanks for reporting this issue. Would there be a way for you to open a codesandbox with a minimal repro explaining your situation? Thanks!

**Comment by atifsyedali** [comment]
Hi,

I think I have a very unique situation in that I have several nested divs and parent divs redraw during drag.  For now, I have implemented DnD myself as we are on a tight timeline. Going to close this issue as the problem was not related to this library.

Thanks.
