### ISSUE TITLE
Option to persist the nativeEvent

### ISSUE THREAD

**Issue by highfield** [react-spring/react-use-gesture#172]
Together with a wheel operation, I need to retrieve the current pointer position relative to the element listening to the events. The aim is to implement a contextual wheeled zoom, centered at the pointer position (such as Google Maps, for instance).

My current attempt is with a combined subscription of `Move` and `Wheel` gestures, as follows:

    const moveRef = React.useRef<number>(0);

    const bindWheel = useGesture({
        onMove: st => {
            const { nativeEvent } = st.event;
            if (nativeEvent) {
                const { offsetX, offsetY } = nativeEvent as MouseEvent;
                moveRef.current = dir === Horizontal
                    ? offsetX
                    : offsetY;
                //console.log("move", moveRef.current)
            }
        },
        onWheel: st => {
            if (onChange && isValidRange(props.lrange)) {
                const factor = st.movement[1] < 0
                    ? scaleDown
                    : scaleUp;

                // ...
            }
        }
    }, { enabled: actualEnabled, }
    )

Now, the pointer location is offered as [offsetX, offsetY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX) by the native event, but to access these properties having a `SyntheticEvent`, I must leverage the `nativeEvent` property.

The problem is that the event should be [persisted before](https://stackoverflow.com/questions/49500255/warning-this-synthetic-event-is-reused-for-performance-reasons-happening-with) the user handler, but that seems not possible.

By digging into your code, I've seen that persisting at the [very first level](https://github.com/react-spring/react-use-gesture/blob/f8d83db79a973fa68937036d1c2b1546ed3cf6d8/src/recognizers/MoveRecognizer.ts#L19) seems working, although I personally don't like this patch:

```
  onMove = (event: UseGestureEvent): void => {
      if (!this.moveShouldRun()) return
      event.persist();  //this works!
    this.clearTimeout()
    this.setTimeout(this.onMoveEnd)

    if (!this.state._active) this.onMoveStart(event)
    else this.onMoveChange(event)
  }

```
I wonder if wouldn't better having an option flag able to instruct a specific handler whether to persist or not (default).

**Comment by dbismut** [comment]
Ciao @highfield, a few things.

1. There's always the option to get native events by using the `domTarget` option and passing a ref to it.

2. The scroll, wheel and move events are debounced, which means that the last event passed can't be queried since it's no longer synced, as [explained in the docs](https://use-gesture.netlify.app/docs/faq#accessing-source-event-triggers-a-warning-in-the-console).

Back to the second point, have a look at https://codesandbox.io/s/blazing-glade-sfoyi. You can query the native event but just make sure you're not doing it when it's the `last` event.

**Comment by highfield** [comment]
@dbismut I used your snippet approach and it is working fine.

Many thanks!
