### ISSUE TITLE
Add example for triggering actions on swipe

### ISSUE THREAD

**Issue by MattFromGer** [react-spring/react-use-gesture#174]
So I need the same thing as discussed in issue #8 
I guess the code has changed a lot since then? Also the linked CodeSandbox is not compiling anymore. Can anybody help me with that?

**Comment by dbismut** [comment]
Hi @MattFromGer, I suppose you've [read the docs](https://codesandbox.io/invite/u0humvdzgcx6hzfb) :)

Essentially you just need to:

```jsx
useDrag(({ swipe: [swipeX, swipeY] }) => {
  if (swipeX === -1) // swipe left
  else if (swipeX === 1) // swipe right

  if (swipeY === -1) // swipe top
  else if (swipeY === 1) // swipe bottom
})
```
