### ISSUE TITLE
Incorrect firing of onDrag when using filterTaps

### ISSUE THREAD

**Issue by lourd** [react-spring/react-use-gesture#176]
I discovered this issue when building the demo for https://github.com/react-spring/react-spring/issues/1026

## Demo

https://codesandbox.io/s/react-spring-inertial-scroll-challenge-qh4wr

## Recording

![scroll jumping example](https://user-images.githubusercontent.com/2012388/82762131-446be680-9dcd-11ea-96c5-4d47446bb1d9.gif)

The steps happening there:

1. touch scroll a bit
2. trackpad scroll to a new position
3. tap on an item

This appears to set the scroll position back to the last position from touch scrolling and then animate it back to the current position. The `onDrag` callback shouldn't be firing at all here since `filterTaps` is enabled. Stranger still that the gesture data doesn't show it as a `first` or `down`.

**Comment by dbismut** [comment]
Hi @lourd, several things here I believe!

1. `filterTaps` doesn't prevent the `onDrag` handler from firing. It just sets a `tap` flag to `true` in the state (similarly to `down`), that you can use as below:

```js
useDrag( ({ tap, first, last }) => {
  if (tap) {
    console.log('this is a tap, and first and last are false', first, last)
    // do your click logic here
    return
  }
  // your drag logic
```

2. About the the glitch you're experiencing, I'm not exactly sure about the exact reason, but I believe it is related to the native scroll inertia continuing after your mouse is released. So, if you throw your wheel, "artificially" stop the container from scrolling by setting its `scrollLeft`, and then release your mouse, the inertia from the original wheel will still continue for a while.

Here's an example that doesn't use `scrollTop / scrollLeft` but that handles both wheel and drag at the same time for reference.

https://codesandbox.io/s/infinite-slideshow-nigoy

All in all, I don't think it's a bug :)

**Comment by dbismut** [comment]
Hi @lourd, I’m closing this for now. But feel free to continue the thread if you still have questions.
