### ISSUE TITLE
React-use-gesture above v5.0.0 not working properly with useSprings

### ISSUE THREAD

**Issue by JCGonzaga01** [react-spring/react-use-gesture#177]
Hi,

Apologies in advance for noob question, this is my first time to create an issue and kinda new to web development.

Basically, I was just trying to implement react-use-gesture but it seems not working properly.
Kindly refer to this codesandbox: https://codesandbox.io/s/late-wood-28pbq
As per checking, the latest version is not working properly but v5.0.0 is.

**Comment by dbismut** [comment]
Please use the sandbox from the Readme of this repo. https://codesandbox.io/s/viewpager-v364z

**Comment by JCGonzaga01** [comment]
Thank you @dbismut
About this, would it be better if we can create or have have a version dependency documentation/reference for this?
It seems react-springs v8 is not properly aligned with react-use-gesture v6 and above.
