### ISSUE TITLE
Type '(event: TouchEvent) => void' is not assignable to  type '(event: TouchEvent<Element>) => void'.

### ISSUE THREAD

**Issue by laclance** [react-spring/react-use-gesture#178]
Using this code I get the error bellow:

```
  const bind = useGesture({ onDrag, onMouseDown, onTouchStart });

  function onMouseDown(event: MouseEvent) {
    console.log('onMouseDown', event);
  }

  function onTouchStart(event: TouchEvent) {
    console.log('onTouchStart', event);
  }
```

Error:

> (property) onTouchStart: (event: TouchEvent) => void
> Type '(event: TouchEvent) => void' is not assignable to 
> type '(event: TouchEvent<Element>) => void'.
> 
> Types of parameters 'event' and 'event' are incompatible.
> Type 'TouchEvent<Element>' is missing the following 
> properties from type 'TouchEvent': detail, view, which, cancelBubble, and 10 more.ts(2322)
> index.d.ts(1498, 9): The expected type comes from property
>  'onTouchStart' which is declared here on type 'UserHandlersPartial'

onMouseDown works fine. I don't get an error with this function but inner function does not get called:
```
  function onTouchStart() {
    console.log('onTouchStart');
    return function (event: TouchEvent) {
      console.log('onTouchStartInner', event);
    };
  }
```

**Comment by dbismut** [comment]
Hey @laclance, did you try using `React.TouchEvent`, `React.MouseEvent`?

**Comment by laclance** [comment]
Ah sorry I forgot to use the React Event.
