### ISSUE TITLE
Type error with react-three-fiber

### ISSUE THREAD

**Issue by maku693** [react-spring/react-use-gesture#182]
Type error occurs with `<mesh>` component of `react-three-fiber` when giving not only callback function but also options to the hooks.

[CodeSandbox to reproduce the issue](https://codesandbox.io/s/beautiful-snyder-gsslh?fontsize=14&hidenavigation=1&theme=dark)

It seems `onPointer*` event handlers of `<mesh>` and `ReactEventHandlers` of `react-use-gesture` is not compatible, but  I think instantiating `ReactEventHandlers` instead of `Fn` from `HookReturnType` is better when specifying no options for the gesture hooks anyway.

Full error messages for reference below:

<details>

```
Type '{ children: Element[]; onMouseDown?: ((event: MouseEvent<Element, MouseEvent>) => void) | undefined; onMouseDownCapture?: ((event: MouseEvent<Element, MouseEvent>) => void) | undefined; ... 45 more ...; ref: MutableRefObject<...>; }' is not assignable to type 'Object3DNode<Mesh, typeof Mesh>'.
  Type '{ children: Element[]; onMouseDown?: ((event: MouseEvent<Element, MouseEvent>) => void) | undefined; onMouseDownCapture?: ((event: MouseEvent<Element, MouseEvent>) => void) | undefined; ... 45 more ...; ref: MutableRefObject<...>; }' is not assignable to type 'Events'.
    Types of property 'onPointerUp' are incompatible.
      Type '((event: PointerEvent<Element>) => void) | undefined' is not assignable to type '((e: PointerEvent) => void) | undefined'.
        Type '(event: PointerEvent<Element>) => void' is not assignable to type '(e: PointerEvent) => void'.
          Types of parameters 'event' and 'e' are incompatible.
            Type 'PointerEvent' is not assignable to type 'PointerEvent<Element>'.
              Type 'MouseEvent<HTMLDivElement, MouseEvent> & Intersection & { intersections: Intersection[]; stopped: boolean; ... 5 more ...; delta: number; }' is missing the following properties from type 'PointerEvent<Element>': pointerId, pressure, tangentialPressure, tiltX, and 6 more.ts(2322)
```

</details>

**Comment by dbismut** [comment]
@maku693, thanks for reporting the issue! Let me check with @drcmda. I'm not sure I understand what you mean with your recommendation I'm sorry, can you please elaborate?

FYI, the handlers from `react-use-gesture` are directly extracted from React's own handlers.

**Comment by maku693** [comment]
Hi @dbismut, thank you for replying!

`useDrag()` returns function returns `HookReturnType<T>`, which is actually `Fn` or `ReactEventHandlers` determined by presence of `domTarget` property of type parameter `T`:

https://github.com/react-spring/react-use-gesture/blob/f8d83db79a973fa68937036d1c2b1546ed3cf6d8/src/hooks/useDrag.ts#L15-L18

https://github.com/react-spring/react-use-gesture/blob/f8d83db79a973fa68937036d1c2b1546ed3cf6d8/src/types.ts#L321-L323

I thought the actual return type of `useDrag` should be the same whether specifying `undefined`, empty object (`{}`) to, or just omit the `config`, since they are treated as an empty object in the implementation, but currently, the return "type" is not the same.

https://codesandbox.io/s/thirsty-yonath-mpkpf?file=/src/index.tsx

`T1` in CodeSandbox above is `Fn`, but `T2` is `ReactEventHandlers`.

I don't know which of `Fn` or `ReactEventHandlers` should be used for empty options, but if `ReactEventHandlers` is the correct type, then types of `onPointer*` handlers of `react-three-fibers` should be adjusted as well to fit with original React's handlers.

**Comment by dbismut** [comment]
@maku693 to put it simply, in your use case (ie no `domTarget`) `bind()` should return a `ReactEventHandlers`.

Therefore I think the issue has two sides:
1. `react-use-gesture` should be fixed to accept extended `Events` (so that they're not restricted strictly to React Event types. Possibly something like:

```ts
type CustomEvent<T extends React.PointerEvent = React.PointerEvent> = T
```

2. `react-three-fiber` should probably distinguish Pointer / Wheel events.

**Comment by maku693** [comment]
Thanks for the explanation, I finally understood the cause of the problem.

I think the first problem isn't necessary for fixing type error if `react-three-fiber` distinguish Click / Pointer / Wheel events properly.
Because `React.PointerEvent` will be a subtype of argument types of `react-three-fiber` event handlers, so original React's handlers fit handlers of `react-three-fiber`.

**Comment by dbismut** [comment]
Yes but if for some reason you need to access an augmented PointerEvent property from r3f inside a hook, react use gesture won’t let you. You could always cast It, but I’ll see if there’s a better solution.

**Comment by dbismut** [comment]
Should be fixed with react-three-fiber `4.2.10` that merges react-spring/react-three-fiber#495 ;) I'll try to work on making react-use-gesture more extensible in v8.

**Comment by drcmda** [comment]
its merged and pushed

**Comment by maku693** [comment]
Thank you! I'll try the new version.

**Comment by dbismut** [comment]
@maku693 maybe the API could be improved, but this is now possible in v8:

```tsx
const bind = useDrag<ReactThreeFiber.PointerEvent>({ event }) => console.log(event.intersections)

// or

const bind = useGesture<{ drag: ReactThreeFiber.PointerEvent; onClick: ReactThreeFiber.PointerEvent }>({
  onDrag: ({ event }) => console.log(event.intersections),
  onHover: ({ hovering }) => { ... },
  onClick: ({ event }) => console.log(event.intersections)
})

**Comment by smashercosmo** [comment]
Do I understand correctly that this is no longer possible in v10?

**Comment by dbismut** [comment]
Hi @smashercosmo sorry for the late response, can you try `10.0.0-beta.23`? Note that the correct syntax should now be, after upgrading to latest fiber version:

```tsx
const bind = useDrag<ThreeEvent<PointerEvent>>(({ event }) => console.log(event.intersections))

// or

const bind = useGesture<{ drag: ThreeEvent<PointerEvent>; onClick: ThreeEvent<PointerEvent> }>({
  onDrag: ({ event }) => console.log(event.intersections),
  onHover: ({ hovering }) => { ... },
  onClick: ({ event }) => console.log(event.intersections)
})
```

**Comment by owenmech-nl** [comment]
@dbismut has there been a regression here potentially? I am seeing a similar type error with handlers on the latest `@react-three/fiber` and `@use-gesture/react`

[Forked original project to reproduce the issue](https://codesandbox.io/p/sandbox/updated-gesture-fiber-c5dk5x)

**Comment by speculees** [comment]
I am also getting type error with handlers on the latest @react-three/fiber and @use-gesture/react
Current workaround: 
```
 const bind = useDrag(({ down, xy: [x, y] }) => { .... }) as () => MeshProps;

**Comment by opeologist** [comment]
also still seeing this issue like @speculees above when attempting to bind pointer events to a mesh
