### ISSUE TITLE
useWheel not triggered on iOS

### ISSUE THREAD

**Issue by riccardolardi** [react-spring/react-use-gesture#183]
`const bindWheel = useWheel(state => onWheel(state));` doesn't trigger on iOS (13.5). Is this a bug?

**Comment by dbismut** [comment]
There’s no wheel on iOS 🙃 unless you’re using a mouse connected to an iPad?

**Comment by riccardolardi** [comment]
@dbismut yeah I figured :) I'm basically looking how to capture the "inertia" scroll event on mobile that's emitted by the touch gesture after releasing it. On desktop it's the same as the wheel event but on mobile (iOS at least) it only triggers during actual drag but not after release

**Comment by dbismut** [comment]
Yeah so wheel isn’t the event you’re looking for. There’s two options: either you create a fake scroll using drag and use decay to simulate inertia. Either you listen to the scroll event (not wheel) and use onTouchEnd to measure the scroll velocity when the finger is released from the screen.

**Comment by jamesvclements** [comment]
@riccardolardi how did you end up approaching this? I'm looking to simulate native iOS horizontal scrolling using the drag gesture or if wheel is easier. @dbismut would you mind sharing what applying decay would look like, or how you might approach this nowadays?
