### ISSUE TITLE
Draggable List should scroll when dragging Item out of View

### ISSUE THREAD

**Issue by vinnichase** [react-spring/react-use-gesture#184]
I modified the draggable list [example](https://codesandbox.io/s/prod-butterfly-dhpz0) to mimic a scrollable list in a mobile app. https://github.com/react-spring/react-use-gesture/issues/101 this helped me to prevent scrolling which would scroll in the opposite direction of my drag.

When the list overflows, I still want to drag the first item to the last position in the list. Hence when I drag the item to the bottom edge, the view should scroll without my finger leaving the dragged item.

What would you propose the most elegant way? I couldn't find anything out there. The closest I got was by calling [scrollIntoView](https://developer.mozilla.org/de/docs/Web/API/Element/scrollIntoView) on the dragged element in the `useGesture` handler.

**Comment by dbismut** [comment]
Hm well I don’t think there’s any magical solution, I believe you would need to scroll your view manually when your dragged item is close to the edge of the scroll, probably using a setInterval with a scroll delta that would depend from how close you’re from the edge. Does that make sense?

**Comment by vinnichase** [comment]
@dbismut Yes it makes sense. Thanks for the input. Since dragging positions the item relative to the content div, its challenging to keep it sticky to the finger/mouse when scrolling.

I will post my solution here.

**Comment by dbismut** [comment]
Hey I’m curious to know if you also need to detect user intent between dragging and scrolling?

**Comment by meetbrij** [comment]
Hi, I am also facing similar challenge. 
I am scrolling my view manually when the dragged item is close to the edge of the scroll, but somehow the scrolling gets faster than dragging so that way when I am scrolling up my pointer reaches the top but the draggable item is somewhere in the middle. 
As Vinnichase mentioned its becoming challenging to keep the draggable item sticky to the finger/mouse scrolling once I reach the edge. 

Will wait for the solution.

**Comment by meetbrij** [comment]
Hi, I somehow managed to find a way out and fix the issue.
Here is my code. You can clone and check.
https://github.com/meetbrij/react-drag-drop-hooks

**Comment by dbismut** [comment]
@meetbrij do you have a sandbox?

**Comment by mindyourlifeguide** [comment]
Also faced with the need for this function. Is its implementation planned?

**Comment by dbismut** [comment]
No. This lib only handles gestures, not how you deal with side effects.
