### ISSUE TITLE
Dragging doesn't work for links in FireFox

### ISSUE THREAD

**Issue by Linksku** [react-spring/react-use-gesture#188]
Here's a fork of one of the examples: https://codesandbox.io/s/floral-snow-3bmkp

When dragging by clicking on a link, the element doesn't follow my mouse. After dragging, the elements end up in the right places. In Chrome, I can fix it by adding either `draggable="false"` or `-webkit-user-drag: none`, but neither of these work on Firefox.

**Comment by dbismut** [comment]
Hey try this (it's using v8 in alpha):

https://codesandbox.io/s/draggable-list-l7z7q

The logic is probably a bit ugly and I'll need to fix this for v8, but links don't drag, while behaving as expected (not firing when dragged, firing and not dragging when clicked).

**Comment by dbismut** [comment]
@Linksku closing this.

**Comment by ClayCooperLA** [comment]
I’ve experienced this same Firefox issue with useDrag and links, this alpha technique works! Thank you!

However, I just ran into a new issue. This doesn’t seem to work with touch anymore. The `down` event is immediately cancelled on touch down. It happens in the same sandbox posted with the new technique: https://codesandbox.io/s/draggable-list-l7z7q (using Chrome device toolbar to emulate touch)

Is there a new option that we might be missing in this example that would allow touch to function the same?

Thank you. So far, I haven’t seen any library that can out do what react-use-gesture and react-spring can to together. :bow:

**Comment by ClayCooperLA** [comment]
Update: I went back to using react-use-gesture 7.0.15 and added onDragStart={(e)=> e.preventDefault()} to the element with {...bind()}.

Solved. Thank you!

**Comment by mbrashid62** [comment]
Discovered this issue exists for SVGs as well.

**Comment by dbismut** [comment]
On Firefox @mbrashid62? Do you have a sandbox?

**Comment by mbrashid62** [comment]
> On Firefox @mbrashid62? Do you have a sandbox?

@dbismut, yeah, in Firefox. I've modified @Linksku's sandbox to replicate the issue I was experiencing in my codebase, https://codesandbox.io/s/sleepy-wildflower-shos7?file=/src/index.js.

You'll notice it actually works partially, but exhibits some weird behavior. I was able to resolve this with, `onDragStart={(e)=> {e.preventDefault()}}`

**Comment by dbismut** [comment]
I believe this is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1376369 and applies to all images 🤷‍♂️
