### ISSUE TITLE
react-three-fiber support

### ISSUE THREAD

**Issue by mvarble** [react-spring/react-use-gesture#196]
It appears that simple `useDrag` examples no longer work with `react-three-fiber` objects. I cloned this [repo](https://github.com/mxro/threejs-test/tree/master/test1), and the example works, until I bump `three`, `react-three-fiber`, and `react-use-gesture`.

**Comment by dbismut** [comment]
Hi @mvarble im on my phone but please have a look at this: https://codesandbox.io/s/react-three-fiber-gestures-8shbu

And possibly this thread https://github.com/react-spring/react-use-gesture/issues/163#issuecomment-622442618

**Comment by mvarble** [comment]
This is great; thanks @dbismut!
