### ISSUE TITLE
Using useDrag inside a swipe-able carousel

### ISSUE THREAD

**Issue by dixoncheng** [react-spring/react-use-gesture#198]
Hi all, I'm using useDrag inside a slide of a swipe-able carousel (https://github.com/xiaody/react-touch-carousel).

How would I disable the carousel swiping when dragging a useDrag element? The carousel component does not support disabling swipe gestures.

I've tried adding `stopPropagation()` on a parent element, but that ended up disabled useDrag as well.

Any ideas?

**Comment by dbismut** [comment]
Please send over a codesandbox with your best shot and we'll try to help.

**Comment by dixoncheng** [comment]
Here you go:
https://codesandbox.io/s/react-use-gesture-simple-gwx9e

Thanks in advance!

**Comment by dbismut** [comment]
Hmm, this works on Chrome desktop: https://codesandbox.io/s/react-use-gesture-simple-tf0fy

```jsx
  const bind = useDrag(({ event, down, movement: [x, y] }) => {
    event.stopPropagation();
    set({ x: down ? x : 0, y: down ? y : 0, scale: down ? 1.2 : 1 })
  })
```

Did you try exploring that route?

**Comment by dixoncheng** [comment]
Thanks, but that didn't work on touch devices though. Wonder why...

**Comment by dbismut** [comment]
I'm on my phone now but did you try setting `touch-action: none` on the dragged element style?

**Comment by dixoncheng** [comment]
`touch-action: none` didn't do anything :(

**Comment by dbismut** [comment]
@dixoncheng you're right sorry, `touch-action` is unrelated in that case. You need to use this config to useDrag:  

```jsx
{ eventOptions: { capture: true } }
```

This seems to work using the Chrome inspector.
https://codesandbox.io/s/react-use-gesture-simple-tf0fy?file=/src/index.js

**Comment by dixoncheng** [comment]
@dbismut Amazing, works perfectly now, you're a lifesaver!
