### ISSUE TITLE
Mobile chrome - do not show/hide the address bar while dragging

### ISSUE THREAD

**Issue by vlopp** [react-spring/react-use-gesture#201]
Currently, vertically dragging an element with `useDrag` shows/hides the address bar on mobile Chrome, which makes for a pretty weird experience - I want to drag the Button down a bit, not have the bar show.

Is there any way to counteract it?

**Comment by dbismut** [comment]
Codesandbox or I won't believe you 😛

**Comment by dbismut** [comment]
Closing this, feel free to comment with a sandbox.
