### ISSUE TITLE
"useWheel" fires twice

### ISSUE THREAD

**Issue by MartinMikusat** [react-spring/react-use-gesture#202]
Here's a codesandbox, wheeling over the blue area increases the "Event count" by 1 and "Gesture count" by 2. 
https://codesandbox.io/s/strange-zhukovsky-s93w1?file=/src/App.js

Here's a short conversation on Discord about this issue, seems to be happening to other people as well.
https://discordapp.com/channels/740090768164651008/740093202987483156/742322504927936592

Tried this with different mice and mouse settings, the behavior stays the same.

**Comment by MartinMikusat** [comment]
Just noticed that wheel wheeling quickly, the "Gesture count" is increased by the same amount as "Event count" + 1. Kind of as if the "useWheelEnd" counted as "useWheel".

**Comment by dbismut** [comment]
Yep well this is by design. `wheel`, `scroll`, `move` are all debounced, so there's a last event that is fired twice to let you know when the gesture ends. If you add `active && gestureListener()` as in https://codesandbox.io/s/funny-dhawan-dgyhz you'll have the right amount of active events.
