### ISSUE TITLE
Something changed with the way 'down' works

### ISSUE THREAD

**Issue by creativiii** [react-spring/react-use-gesture#209]
Sorry about the really vague title but I honestly have no idea how to explain this.

I modified the official react-spring carousel example to better fit my needs, it works great, that is until I upgrade to the latest `react-use-gesture`.

In my original version I was using `6.0.14`, in that version as soon as the user lifted the mouse `down` would be changed to false which meant I could use something along this:

```
      if (!down) {
        index.current += ((-xMove + (width + xMove)) / width) * (xDir > 0 ? -1 : 1)
        cancel()
      }
```

This would allow me to set values as soon as the finger was not on the screen anymore. However with the latest version `7.0.16`, the way `down` works seems to have changed.

In [this example](https://codesandbox.io/s/improved-carousel-envjk?file=/src/Slider.js:3075-3221), I use the code above, but on `7.0.16`, down doesn't become `false` immediately, which means my if statement ends up being called twice.

What's my best option to fix this?

**Comment by dbismut** [comment]
Hi @creativiii what makes you believe that `down` doesn't become `false` immediately? Nothing should have change regarding the down behavior, it is triggered on `mouseup` / `touchend`, there's no reason why those events wouldn't be passed synchronously to the handler...

**Comment by creativiii** [comment]
> Hi @creativiii what makes you believe that `down` doesn't become `false` immediately? Nothing should have change regarding the down behavior, it is triggered on `mouseup` / `touchend`, there's no reason why those events wouldn't be passed synchronously to the handler...

Actually the problem seems to be that despite `down` being set to false, the gesture runs twice.

I guess my evidence is mostly circumstantial, but as the example shows with `7.0.16` dragging the carousel causes it to skip two frames every single time. While the same code on `6.0.14` works perfectly.

Putting a console log in the if statement clearly shows it running twice when down is set to false which didn't use to happen.

Sorry for the confusion!

**Comment by dbismut** [comment]
@creativiii I'm not sure why you cancel the drag event when `down` is `false`. This doesn't make a lot of sense to cancels something that is already finished.

The `cancel` function resets all state attributes (like `down`, `active`, etc.) and runs the handler **in the next frame**.

What happens in your case is that the gesture ends, you cancel the gesture, which then triggers another run of your handler with `down` obviously set to `false`. So all this is expected. The lib could detect that the gesture is already ended and prevent cancel from firing, but I don't think it's necessary.

In your case, you need to remove the `cancel` function. If you come from the viewpager example, `cancel` is used in there to force switch indexes while the user is dragging and without him needing to release the drag. That's a different use case.
