### ISSUE TITLE
Direction is wrong

### ISSUE THREAD

**Issue by arvigeus** [react-spring/react-use-gesture#32]
This is hard to reproduce, but sometimes `direction` is [0, 0] although the mouse had moved. Here is a video of that: https://youtu.be/YfDXwAw9mr4

`react-with-gesture` v4.0.2

```javascript
<Wrapper>
  {children.map((child, index) => (
    <Gesture key={index}>
      {(props) => (
        ...
      )
    <Gesture key={index}>
</Wrapper>

const Wrapper = styled.div`
  position: relative;
  display: flex;
  overflow: hidden;
  width: 100%;
  height: 100%;
  align-items: center;
  justify-content: center;
`;
```
(if this is useful at all)

**Comment by dbismut** [comment]
@arvigeus we've just released a beta of v5.0.0 (react-use-gesture@5.0.0-beta.3) that might correct your problem.

However, there's quite a few api changes that are mentioned [here](https://github.com/react-spring/react-use-gesture/blob/5.x/CHANGELOG.md), dropping render-props and relying solely on hooks might affect you I'm afraid.

```jsx
const bind = useGesture({ onDrag: () => {} }, {...config})
```

**Comment by dbismut** [comment]
If you have a codesandbox with the old code I'd be happy to migrate it to hooks to see if it's solved.

**Comment by arvigeus** [comment]
Thank you for your kindness! The code is too convoluted. Unless you hate life and free time, I think I'll spare you "the pleasure".

**Comment by dbismut** [comment]
Haha fair enough. Well if you use this lib again with hooks and stumble upon the same problem let me know!
