### ISSUE TITLE
Compatibility issue with react-spring 8.x

### ISSUE THREAD

**Issue by tkvw** [react-spring/react-use-gesture#35]
The example https://codesandbox.io/embed/zq19y1xr9m does not seem to work with with the latest versions of react-spring and react; @see: https://codesandbox.io/s/j2nl5z3m45 . Any ideas?

**Comment by drcmda** [comment]
ah, good catch, decay was an experimental feature i was working on. i will fix it ...

**Comment by tkvw** [comment]
Any update?

**Comment by drcmda** [comment]
I was so busy i couldn't look at it still. Just fixed it: https://codesandbox.io/s/zq19y1xr9m?from-embed
