### ISSUE TITLE
Window not defined in default prop

### ISSUE THREAD

**Issue by jccedre** [react-spring/react-use-gesture#44]
Looks like version 4.0.7 introduced a default prop for window but my SSR rendering app is now crashing because there isn't a catch for when window is not defined. For the time being I just rolled back to version 4.0.5 and everything is working fine.

**Comment by drcmda** [comment]
Oh, it was caused by this PR https://github.com/react-spring/react-with-gesture/pull/43/files

Do you know how to solve it?

**Comment by xD3CODER** [comment]
Same issue here

**Comment by drcmda** [comment]
i reverted the commit and made a patch

**Comment by jccedre** [comment]
I think a possible solution may be to use ternary operator to check if window is undefined.  I am able to confirm this worked in my case with Gatsbyjs when running the build command. 

```
var defaultProps = {
    window: typeof window !== 'undefined' ? window : null,
    touch: true,
    mouse: true,
    passive: {
    passive: true
}
```

**Comment by janbaykara** [comment]
@jccedre would you like to submit that as a PR?

**Comment by dbismut** [comment]
Hey @jccedre we've just released a beta of v5.0.0 (react-use-gesture@5.0.0-beta.3) that should implement your PR.

There's quite a few api changes that are mentioned [here](https://github.com/react-spring/react-use-gesture/blob/5.x/CHANGELOG.md), some of them might affect you.

```jsx
const bind = useGesture({ onDrag: () => {} }, {...config})
```

**Comment by jccedre** [comment]
@dbismut wow! So happy with the direction v5.0.0 is going in. I took a look at the code and hopefully catching window inside the defaultConfig should do the trick for SSR. Thank you for implementing that fix. If there is anything I can do to help let me know. I am happy to support this project!

**Comment by dbismut** [comment]
Good to hear! 5.0.0 introduces many new gestures, and hasn't been thoroughly tested on many browsers yet, so if you happen to try it let us know if there's anything that breaks. Other than that yes, it should do the trick, since we're only adding listeners to the `window` when the user starts the drag (i.e. presses the element), and that can't happen in the server 😅
