### ISSUE TITLE
5.x Bind only stores last args

### ISSUE THREAD

**Issue by mrsimb** [react-spring/react-use-gesture#49]
I have one useGesture handler for multiple items. I use bind(itemIndex) for each item.
All handlers created by bind now seem to store the last itemIndex passed to bind, instead of unique for each one (like it was in 4.x).

**Comment by dbismut** [comment]
You’re right! I think I know how to fix this. Shouldn’t take long!

**Comment by dbismut** [comment]
Hi @mrsimb this should be fixed (and tested) in `@5.0.0-beta.5`!
https://codesandbox.io/s/935470jo44

**Comment by mrsimb** [comment]
Neat! Just tried it, works great!
Can we close this issue now?
