### ISSUE TITLE
Support for trackpad-based moving and pinch & zoom

### ISSUE THREAD

**Issue by niieani** [react-spring/react-use-gesture#51]
I noticed that current version only works with real touch devices. It would be great if we could support at least some multi-touch gestures on trackpads, like moving around and pinch to zoom.

Here's an article that explains how to achieve that cross-browser: https://medium.com/@auchenberg/detecting-multi-touch-trackpad-gestures-in-javascript-a2505babb10e

**Comment by dbismut** [comment]
Good point, I believe this is proprietary to WebKit but it shouldn’t be to hard to implement in the future. I’ve referenced the feature in the roadmap issue right there:

https://github.com/react-spring/react-use-gesture/issues/45

**Comment by niieani** [comment]
Great to hear it's on the roadmap! 👍 

The two basic gestures (moving and pinching) work cross-browser via a sanctioned "hack" (e.g. Google Maps uses it), though no individual finger tracking is possible. That article I mentioned actually mentions how it's implemented :)

**Comment by dbismut** [comment]
Ok I’ll have a closer look! Thanks for the tip 👊

**Comment by dbismut** [comment]
Hey @niieani I'm trying the example mentioned in the article you sent (https://multi-touch-trackpad-gesture.stackblitz.io/) and although this works in Safari (because of `gesturechange` I guess), it doesn't seem to work on Chrome nor Firefox. Does it for you?

Anyway, I'm considering implementing trackpad gestures at least for Safari but React doesn't support proprietary APIs so I'd have to handle events manually.

**Comment by niieani** [comment]
Hi @dbismut it works for me on: 

- macOS + Chrome (zoom & pan)
- macOS + Firefox (zoom & pan)
- macOS + Safari (zoom & pan & rotation)

I'm not sure how good the support on Windows trackpads is though (if at all).

**Comment by dbismut** [comment]
That's really weird, what's the trackpad you're using? Can you also let me know versions of the browsers and OS?

On my end, with a 2016 MacBook Pro, MacOS 10.14.4, Chrome 75.0.3770.18 (beta), Firefox 67.0b18 (beta) it just scrolls through the page with no effect on scale.

**Comment by niieani** [comment]
@dbismut I'm using the built-in trackpad of MacBook Pro (15-inch, 2018) and was testing on dev versions of Chrome and FF. No idea why it's not working for you, maybe it's due to some setting/configuration change? I have another MacBook Pro 13" from 2015, I can test it there if you'd like?

**Comment by dbismut** [comment]
That would be awesome, I’ll also run some tests at agency. You don’t actually need to press ctrl right?

**Comment by niieani** [comment]
@dbismut No, in fact pressing CTRL has no effect for me. Only actual pinching/panning triggers that meta change. I'll have a look over the weekend.

**Comment by dbismut** [comment]
@niieani forget it, it works now for some reason, I'll have a shot at this this week-end.

**Comment by dbismut** [comment]
Hey @niieani here's a first attempt that should work on Safari (scale and rotation) and Chrome (scale only): 

[Full Screen](https://54wvx0w1z4.codesandbox.io)
[Code](https://codesandbox.io/s/54wvx0w1z4) - gestures won't work in the iframe preview I think

Implementation is a bit clumsy at the moment, also for some reason I had to preventDefault on document gestures to prevent Safari showing tab overview on unzoom (I don't have to do this when I test locally)

**Comment by niieani** [comment]
Hey @dbismut great! There's one issue on Chrome for me, when I zoom, sometimes the native zoom functionality also gets triggered, so I'm zooming the viewport together with the element. Not sure if I said it clearly?

**Comment by dbismut** [comment]
It does. I think it has to do with the gesture being captured by the document instead of the element, it happens to me when I’m unzooming and the element becomes small enough so that my mouse is not over it anymore. Would that make sense?

**Comment by niieani** [comment]
@dbismut yeah, although when zooming in it also happens so that sometimes it's currently hard to say if I'm zooming the page or triggering the component.

**Comment by dbismut** [comment]
Just published `5.1.0-beta.2`, example has been updated to use it: https://54wvx0w1z4.codesandbox.io/

I think you’ll encounter the same issues. If you wish to get your hands dirty don’t hesitate to PR on branch #next !
