### ISSUE TITLE
Wrong event.button

### ISSUE THREAD

**Issue by mrsimb** [react-spring/react-use-gesture#57]
Try to drag the square with middle or right mouse button.
Every event that is not first or last will have event.button === 0 (left button).
https://codesandbox.io/s/strange-surf-g4xsy

**Comment by dbismut** [comment]
Hey @mrsimb thanks for reporting the issue. I think I understand what you mean, however the `event` attribute that is returned to you in the gesture handler is the untouched source event, meaning we can't "fix" any of its attributes. It's literally the event created by the browser, it can't be wrong 🙃

However, your issue makes me realize that we're firing the drag gesture without checking which button is pressed.

**Comment by mrsimb** [comment]
> we're firing the drag gesture without checking which button is pressed.
This is normal. I wanted to use middle mouse button for panning, and left for dragging items.
I think i got it wrong, as i can just call cancel() if first event is fired with wrong button.

I am closing this as it is not a library issue.

**Comment by dbismut** [comment]
I'm interested in this use case though. Are you handling the panning through `react-use-gesture` or otherwise?

We could have a `button` attribute that would be set when drag starts, and which would tell you which button has initiated the drag event all along. You could rely on that attribute to pan or drag depending on your logic. Would that be helpful?

**Comment by mrsimb** [comment]
> Are you handling the panning through react-use-gesture

Yes, i have a background div which is draggable with any mouse button.
And there are item divs, which are only draggable with left mouse button (and the event propagation is stopped, to prevent simultaneous panning).

We already have touches, button will be a nice addition.

**Comment by dbismut** [comment]
You can try installing `yarn add react-use-gesture@next` if you don't mind (it shouldn't break anything but it's a major refactoring so some there might be side issues)

It exports `buttons` which should give you the correct button pressed for any mouse event.

See this as an example: https://codesandbox.io/s/54wvx0w1z4
Dragging the card with the left button has inertia while there's no inertia when you drag with the right button.

This version also "cancels" the gesture if no buttons are pressed during mouse move, which could happen if you right click the div, trigger the context menu and then move your mouse with no button pressed.

Finally, I think I know why `button` doesn't work in your case. From the [docs](https://developer.mozilla.org/fr/docs/Web/API/MouseEvent/buttons):

> Do not confuse this property with the MouseEvent.button property. The MouseEvent.buttons property indicates the state of buttons pressed during any kind of mouse event, while the MouseEvent.button property only guarantees the correct value for mouse events caused by pressing or releasing one or multiple buttons.

**Comment by mrsimb** [comment]
Works good for me

> MouseEvent.button property only guarantees the correct value for mouse events caused by pressing or releasing

Oh, i missed that. Thanks for the explanation!

> This version also "cancels" the gesture if no buttons are pressed during mouse move, which could happen if you right click the div, trigger the context menu and then move your mouse with no button pressed.

Never noticed that one

> PS: btw, the next version also includes pinching gestures on trackpads.

Awesome! Have no trackpad though, so can't check this out.
