### ISSUE TITLE
Arrow functions are not supported on IE11

### ISSUE THREAD

**Issue by isBatak** [react-spring/react-use-gesture#60]
I managed to fix react-sping on IE11 by using `react-spring/web.cjs`, but `react-use-gesture` doesn't have `.cjs` module and it's using arrow functions which are not supported in IE11. 
Could you make '.cjs` bundle also, or transpile arrow functions?

**Comment by dbismut** [comment]
Hey @isBatak this should be fine in `react-use-gesture@next`, can you please confirm?

**Comment by isBatak** [comment]
Thx @dbismut it works with `5.1.0-beta.6` version!

**Comment by dbismut** [comment]
Cool! In the meantime, I've bumped it to... `5.1.0-beta.9` since then as I had issues with TypeScript. Hopefully it would still work for you.
