### ISSUE TITLE
React synthetic DnD events break the interaction.

### ISSUE THREAD

**Issue by schabluk** [react-spring/react-use-gesture#61]
Following the topic started in the [#45](https://github.com/react-spring/react-use-gesture/issues/45).

@dbismut please, see this example: https://codesandbox.io/s/eloquent-yalow-0kv87

I am using `draggable` attribute together with `onDragOver` to capture the index of the element over which I'm dragging. That breaks the spring animation. If you set `draggable={false}` the springs are working correctly, but then `onDragOver` doesn't.

**Comment by dbismut** [comment]
I see. Silly question: are you using draggable _just_ for the purpose of showing the ghost of the dragged div or do you on using dnd capabilities?

Could you please describe what is your targeted _ideal_ behavior? You might not need `useGesture` in that situation and on rely solely on dnd handlers to trigger animations?

**Comment by schabluk** [comment]
@dbismut 
> are you using draggable just for the purpose of showing the ghost of the dragged div 

No, I would like to avoid the native 'ghost' effect.

> what is your targeted ideal behavior?

I would like to implement a sortable list, just like the one from examples: https://codesandbox.io/s/r5qmj8m6lq.

The issues is, that my elements are not fixed with height, so to calculate `curRow`, I would have to use very complex logic, like tracking Bounding Client Rect of every element, and calculating dragging direction. With native `onDragOver` handler, this is trivial.

> You might not need useGesture in that situation and on rely solely on dnd handlers to trigger animations?

Yes, I think that might be the case here. However, it would be much easier for me to useGesture, as it has such a nice interface :)

**Comment by dbismut** [comment]
I understand. On top of my head i don’t think it would require a lot of work, let me check this when I have some time this week!

**Comment by dbismut** [comment]
Btw direction should be given to you out of the box, just saying ;)

**Comment by schabluk** [comment]
@dbismut if you could give me some hints, on where this logic is implemented, maybe I could contribute. Can't promise though ;)

**Comment by dbismut** [comment]
That would be awesome! I'm currently iterating on the #next branch that is a major refactoring rewritten in Typescript (I'm not exactly sure why I did this, it's more an excuse for me to learn TS ^^). 

Anyway, the [file that handles drag stuff is this one](https://github.com/react-spring/react-use-gesture/blob/next/src/recognizers/DragRecognizer.ts). However, I need to setup a real-life testing environment similarly to `react-spring` to make development easier. So it's not a contribution-friendly project atm, I need to fix this asap :)

**Comment by schabluk** [comment]
@dbismut sounds challenging! Let me see what I can do :)

**Comment by dbismut** [comment]
@schabluk I've set up a repo similar to `react-spring-examples` for `react-use-gesture` and that allows seamless development: https://github.com/dbismut/react-use-gesture-examples

Just copy this repo in the same location as the location of your fork of `react-use-gesture`, install dependencies and you should be good to go. I've added your example in the `/tests` directory, you just have to _activate_ it ([per these instructions](https://github.com/dbismut/react-use-gesture-examples#contributors)).

Let me know if you need any help.

**Comment by dbismut** [comment]
Hey @schabluk I had a quick shot at it and tbh, I'm not sure there's a lot we can do to make it work fine. This is what I get when using `onDrag` handlers:

![onDrag](https://user-images.githubusercontent.com/5003380/58943123-65cc6080-877f-11e9-9feb-d1635345f21e.gif)

The ghost can't be removed cleanly (I've seen some hacks on SO but they don't feel right). I'd try to find another solution for detecting the index position without relying on the height of the elements.

**Comment by schabluk** [comment]
@dbismut AFAIK the ghost can only be removed by setting transparent pixel as a preview:

```javascript
const preview = new Image()
// Transparent pixel.
preview.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='

<animated.div
  draggable
  onDragStart={event => {
    event.dataTransfer.setData('text', '...')
    event.dataTransfer.setDragImage(preview, 10, 10)
  }}>
  {children}
</animated.div>

```

**Comment by dbismut** [comment]
Oh ok :)

Well if you want to make some tests I've just published the [#next-dnd branch](https://github.com/react-spring/react-use-gesture/tree/next-dnd) that adds the `onDnd` handler. It hides the ghost using the sample of code you provided above so no need to add it. It also sets `draggable` to `true` in the object returned by the `bind` function so no need to add it manually.

You just have to change your code to:

```jsx
const bind = useGesture({
  onDnd: ({ args: [originalIndex], down, delta: [, y] }) => { // <-- using onDnd handler
    const curIndex = order.current.indexOf(originalIndex)
    const curRow = clamp(
      Math.round((curIndex * BASE_HEIGHT + y) / BASE_HEIGHT),
      0,
      items.length - 1
    )
    const newOrder = swap(order.current, curIndex, curRow)

    setSprings(style(newOrder, down, originalIndex, curIndex, y))
    if (!down) order.current = newOrder
  },
})
```

I've tested it and I'm running into some lags after a few drag overs.

**Comment by schabluk** [comment]
> I'm running into some lags after a few drag overs

Hi! I've setup my sandbox with the next-dnd branch, and yes there are some issues with lags. 

As I mentioned before, there are some quirks with Drag events in comparison to Mouse events. For example, the `onDrag` event is emitted, event if the cursor is still, and that probably generate lags.

Also, I noticed that the cursor coordinates (*x, *y) after the last `drag` event are set to zero (which is weird and should not occur), so the `delta` from kinematics has wrong value when the item is dropped.

I will try with hybrid approach - using `onDragStart` `onDragEnd` from DnD API, and `onPointerMove` to trigger `onChange`.

**Comment by dbismut** [comment]
Hey @schabluk I'm not sure that helps, but I had an idea of using `onMouseOver` rather than `onDragOver`, setting `pointer-events` to `none` for the dragged element.

https://codesandbox.io/s/summer-thunder-fr6o8

Maybe you had thought of this, I'm not exactly sure how to make that work for touch, but there might be something here?

**Comment by schabluk** [comment]
> using `onMouseOver` rather than `onDragOver`

Hay, that worsk suprisingly well! I discovered the issue with `onDragOver` and the issue is, that when you drag an element over another, the `onDragOver` is not triggered, because the cursor is over dragged element... so I think the `onMouseOver` is only option here.
