### ISSUE TITLE
OnDrag does not always detect on release

### ISSUE THREAD

**Issue by ddennis** [react-spring/react-use-gesture#62]
Hi 
I have made a quick [demo](https://codesandbox.io/s/boundariesthrow-o1dvp)

I am using a mouse and alot of times OnDrag does not detect that have have released the mouse button, which makes the content stick to the mouse. 

I am missing something?

Otherwise great library.

**Comment by dbismut** [comment]
Hey, I’ll have a look tomorrow. In the meantime, could you try if it does the same with 5.1.0? It’s currently in beta but some minor bugs have been fixed (onDrag now makes sure there is always a button pressed).

**Comment by ddennis** [comment]
Thank you. 

Using version 5.1.0.beta.9 seems to fix the button released bug. But dragging is buggy seems delta is not updating correctly. 

I dont experience any difference using version 5.1.0 

[demo](https://codesandbox.io/embed/boundariesthrow-o1dvp)

**Comment by dbismut** [comment]
Hey @ddennis, latest beta version is `5.1.0-beta.9` (I'm not sure what is 5.1.0 😬). I'm testing your latest sandbox with Chrome and I'm not sure what's wrong? Can you please describe the expected behavior?

**Comment by dbismut** [comment]
@ddennis 5.1.1 is out FYI.

**Comment by ddennis** [comment]
@dbismut  Thanks alot - seems to have fixed it.
