### ISSUE TITLE
Renamed repo

### ISSUE THREAD

**Issue by leantide** [react-spring/react-use-gesture#63]
Not sure you can do anything about it or not, but when you renamed your repo from 'react-with-gesture' to 'react-use-gesture', there was of course no ```npm outdated``` or ```yarn outdated``` indication that I needed to upgrade.

**Comment by leantide** [comment]
Just FYI.

**Comment by dbismut** [comment]
Hey @leantide thanks! I'm not sure what we can do about this. Also note `react-with-gesture` provided render-props api which is removed from `react-use-gesture`, so I'm not sure what should be the best strategy here for people that didn't use hooks.

@drcmda any idea?

**Comment by leantide** [comment]
Just a little side note. 

I also observed that for react-with-gestures, all subsequent onDrag handler events had access to the  parent props of the wrapping parent function which used useGesture that were available when it was first called, something like a singleton. But react-use-gestures more normally seems to use a call stack of the props corresponding to the prop values each time the useGestures was called.

This would make no difference to those completely switched over to hooks, since useRef would give access to current state. But since I am integrating a hybrid of hooks and MobX class state, v5 broke my original class-hook integration. Was able to fix it once I understood the difference.

**Comment by drcmda** [comment]
@dbismut Yes, that was the reason, hooks are such a radical api change that letting "with-gesture" stand as is seemed like a good way to me. But going hooks as the primary api and then continuing with that name didn't seem good and i had lots of requests asking for "use" instead.

@leantide Hybrids are indeed a sore spot atm, sorry for the trouble. I had the same problem in react-spring, it's not easy to merge the two, ultimately and with the little time we can spend we would just like to concentrate on the api that seems like the best fit. Glad you fixed it!

**Comment by dbismut** [comment]
@leantide I think this is kinda documented in the [changelog here](https://github.com/react-spring/react-use-gesture/blob/master/CHANGELOG.md#improved-3) (I just fixed the code as it had an error in it tbh):

```jsx
const [dragCount, setDragCount] = useState(0)
const bind = useGesture({
  onDrag: ({ first }) => {
    console.log(dragCount) //<-- count will be up to date
    if (first) setDragCount(dragCount + 1)
  },
})
```

But it might be a breaking change rather than an improvement indeed.

**Comment by leantide** [comment]
I see now. Thanks.
