### ISSUE TITLE
Module '"../../../node_modules/react-use-gesture/web.cjs"' has no exported member 'useGesture'

### ISSUE THREAD

**Issue by garkin** [react-spring/react-use-gesture#64]
`"react-use-gesture": "^5.1.1"`

```ts
import { useGesture } from "react-use-gesture";
```
```
ERROR in /home/src/app/view/app.view.tsx
./src/app/view/app.view.tsx
[tsl] ERROR in /home/src/app/view/app.view.tsx(23,10)
      TS2305: Module '"../../../node_modules/react-use-gesture/web.cjs"' has no exported member 'useGesture'.
ℹ ｢wdm｣: Failed to compile.

```

**Comment by dbismut** [comment]
I’ll be working on this on Wednesday. Sorry about this!

**Comment by timuric** [comment]
Downgrading to 5.1.0 seems to help

**Comment by dbismut** [comment]
@timuric @alihassan0 @garkin  This should be fixed in `5.1.2`. I'm no expert in TS so if you anyone wants to have a look, here's a warm welcome :)

**Comment by garkin** [comment]
Release commit is not tagged.
https://github.com/react-spring/react-use-gesture/releases

**Comment by dbismut** [comment]
Done now @garkin. Sorry to ask, but how is this useful? I'm a bit new to managing repos, just curious...
