### ISSUE TITLE
module not found for "extends" and "objectWithoutPropertiesLoose" 

### ISSUE THREAD

**Issue by pavel1860** [react-spring/react-use-gesture#67]
```
ERROR in ./node_modules/react-use-gesture/web.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/extends' in '/Users/pavel/Developer/Epistema/MentWebClient/node_modules/react-use-gesture'
 @ ./node_modules/react-use-gesture/web.js 2:0-58 61:9-17 70:9-17 86:9-17 101:9-17 235:8-16 236:8-16 237:10-18 238:9-17 239:9-17 301:13-21 389:23-31 392:10-18 421:29-37 440:9-17 481:25-33 486:31-39 496:9-17 528:25-33 533:31-39 543:9-17 573:25-33 578:31-39 588:9-17 618:23-31 637:23-31 640:16-24 713:23-31 716:10-18 740:29-37 753:9-17 793:25-33 798:31-39 810:9-17 834:9-17 851:29-37 864:9-17 912:20-28 941:19-27 942:16-24 943:20-28 957:20-28 1048:30-38
```

getting this error for "extends" and for "objectWithoutPropertiesLoose". I do have the "extends" file but its under `@babel/runtime/helpers/extends` without `esm`. 
Im using typescript for this project, do you know how can I fix this issue?
thanks

**Comment by dbismut** [comment]
Hey, thanks for reporting the issue. Is there a way to set up a reproduction repo somewhere?

**Comment by pavel1860** [comment]
it's a little bit problematic since it is a part of the application that I can't upload into a public repository. but after I tried to create a fresh project with `create-react-app` it was ok. 
I believe it's because there is no `esm` library in my `@babel/runtime/helpers` folder.

**Comment by dbismut** [comment]
I'm not a big expert on rollup build configs, is there anything you would suggest to fix this?

**Comment by sisp** [comment]
I'm having the same issue with [Parcel](https://parceljs.org/) in a tiny example app that accompanies a library I'm writing which uses `useGesture`.

How about using [tsdx](https://github.com/palmerhq/tsdx) by [Jared Palmer](https://github.com/jaredpalmer) et al., who is also the author of [Formik](https://github.com/jaredpalmer/formik), instead of a handwritten Rollup config etc.? tsdx is similar to [CRA](https://github.com/facebook/create-react-app) but for Typescript (component) libraries. I've been using it for some time with much joy.

**Comment by dbismut** [comment]
That looks great @sisp! Let me check what I can do.

**Comment by dbismut** [comment]
Hey, I've made an attempt to use `tsdx` (thanks @sisp) on the [tsdx branch](https://github.com/react-spring/react-use-gesture/tree/tsdx), and released it under `5.1.3-beta.1` on `npm`.

Can you let me know if this fixes it? Also, I'm pretty sure the way I handled TypeScript definitions can be optimized, I also feel the definition for `useGesture` is a bit messy.

**Comment by sisp** [comment]
Thanks a lot @dbismut! I'm not getting the error anymore.

**Comment by dbismut** [comment]
Cool! I’ll iterate a bit on this branch until I’m more satisfied with TS definitions and I’ll merge into master.

**Comment by sisp** [comment]
Sure, thanks for your efforts!

**Comment by dbismut** [comment]
5.1.3 is now released, hopefully this still works!
