### ISSUE TITLE
Guidance for usage in class components

### ISSUE THREAD

**Issue by hwinkler** [react-spring/react-use-gesture#68]
Is it possible to use `react-use-gesture` in class components? All the examples use function components, and when I try passing a ref to `useGesture` in `componentdidMount`, I see errors in the console:
```react-dom.development.js?61bb:55 Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

Pretty sure my case is (2), breaking the Rules of Hooks, since I'm using React & react-dom 16.8.3, and I see that hooks may only be called from function components.

If there is a pattern for using `react-use-gesture` is a class component, any guidance appreciated.

**Comment by dbismut** [comment]
Unfortunately `react-use-gesture` can only be used with hooks and therefore in functional components. It shouldn’t be too hard to wrap the hook in a functional component that then renders the class component you need.

In case that doesn’t work out for you, there’s the legacy `react-with-gesture` that only supports drag but that offers render props components.

**Comment by hwinkler** [comment]
Understood. Thanks. I'm having success wrapping in a functional component.
