### ISSUE TITLE
onWheel handler not called on wheel events

### ISSUE THREAD

**Issue by orouz** [react-spring/react-use-gesture#69]
Hey there! 

first of, gigantic kudos! this lib is super useful. thank you! 

i've noticed a case where the `onWheel` event handler is not getting called while using `bind()`
as opposed to attaching an event listener via React (`onWheel`) which does result in the handler being called. 

[demo](https://codesandbox.io/s/serene-shaw-1slmk?fontsize=14)

is this a bug or am i doing something wrong? 
if it's not i'll close it and be on my way to stackoverflow... :)

thanks again for the hard work! really enjoying making stuff with this tool.

**Comment by dbismut** [comment]
Hey @orouz, thanks for the kind words, much appreciated. You forgot to use the spring value somewhere. Like:

```jsx
{colors.map(i => {
  return <animated.div style={{ transform: y.interpolate(y => `translateX(${-y}px)` }}>{i}</div>
})}

// animated should be imported from react-spring
// import {animated, useSpring} from 'react-spring'
```

Does that make sense?

**Comment by orouz** [comment]
yep that makes total sense. sorry mate!
