### ISSUE TITLE
Breaks bundlephobia

### ISSUE THREAD

**Issue by heygrady** [react-spring/react-use-gesture#70]
https://bundlephobia.com/result?p=react-use-gesture

I rely on bundlephobia for evaluating new packages. Got the following error:

> **MissingDependencyError**
> This package (or this version) uses `@babel/runtime/helpers/esm/extends` and `@babel/runtime/helpers/esm/objectWithoutPropertiesLoose`, but does not specify them either as a dependency or a peer dependency

**Comment by dbismut** [comment]
Hey, I think this is a duplicate of #67, can you try installing `react-use-gesture@beta` see if this fixes it?

**Comment by dbismut** [comment]
Fixed in 5.1.3
