### ISSUE TITLE
Swipe getures?

### ISSUE THREAD

**Issue by skrichten** [react-spring/react-use-gesture#71]
Curious, why are there are no handlers for basic swipe gestures?

**Comment by dbismut** [comment]
Hey @skrichten, good question thank you! Actually it’s pretty easy to handle swipes in all directions from the `onDrag` handler, using `last` and `vxvy` which gives velocity per axis.

So horizontal swipes could be handled like so:

```js
useGesture({
  onDrag: ({ vxvy: [vx], last }) => {
    if(last && vx > 0.3) {
         // swipeLeft
    }
    else if (last && vx > 0.3) {
      // swipeRight
    }
  }
)}
```

I've made a small carousel utility that uses swipe, you can see the related bit of code [here](https://github.com/dbismut/react-soft-slider/blob/1e9cb34e8743c4226f5765a1d31fd3a599de80f1/src/index.js#L173).

I'll add a codesandbox example for swipe though, it is indeed an important feature.

**Comment by skrichten** [comment]
Cool, thanks for the examples!

**Comment by dbismut** [comment]
For reference, here is a working example that was added to the readme: https://codesandbox.io/s/crimson-dawn-pzf9t

**Comment by georgeawwad** [comment]
Hi with the latest release I'm not able to get swipe gestures working within onDrag, but touchpad swipe gestures work with onWheel. Is this intentional? The above examples don't work for me.
