### ISSUE TITLE
Supporting passive event listeners and preventDefault()

### ISSUE THREAD

**Issue by mpolichette** [react-spring/react-use-gesture#76]
Hey guys, your project rocks.

I noticed that you support a config value for `{ event: { passive: true } }`.  However in the basic usage of `useGesture` (and others), your package doesn't actually do the event binding.  So the event binding ends up not being passive except for the few global bindings (for drag).

I think this is fine and once you return the bindings its outside this packages scope.  

The good news is that since you already support binding to external dom/refs, this issue is already resolved!  Using the `domTarget` config will actually bring binding back into the hooks scope!

I fought this issue for a longer than I should have, and wish I'd have found an issue like this one while I was searching... So I'm creating it! :) 

Feel free to close, but if we're looking for a resolution, I think we could add a note in the readme stating that the `passive` config value will only apply to most of your bindings if you use `{ domTarget: myRef }` and `React.useEffect(bind, [bind])`

I could PR the issue to FAQ, but i'm not sure how F it is :)

**Comment by dbismut** [comment]
Hi @mpolichette, thanks for the kind words and reporting the issue. You're absolutely right. React [doesn't support passive events](https://github.com/facebook/react/issues/6436) (yet).

Feel free to add an item to the FAQ, might not be very frequent but it's been in the back of my head for a while, it would be great if it was clarified once and for all!

**Comment by mpolichette** [comment]
I just pushed up a PR for the FAQ [#77].  You might be right about touch events, I ran into this for calling `preventDefault` on wheel events.

**Comment by dbismut** [comment]
That’s perfect! Thanks so much for this :)
