### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.

### ISSUE THREAD

**Issue by rejifald** [react-spring/react-use-gesture#82]
Error: `[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.` occurs when adding pinch gesture
Example
```
	const bindPinch = usePinch((event) => {
		console.log(event);
	}, {
		event: {
			passive: false,
		},
	});
```
My goal is - handle macbook touchpad pinch gesture, and prevent default behavior.

**Comment by rejifald** [comment]
You can see an example of the issue here https://codesandbox.io/s/9o92o24wrr
Try zoom picture by pinch gesture.

**Comment by dbismut** [comment]
Hi, please make sure you read [this from the readme](https://github.com/react-spring/react-use-gesture#why-am-i-getting-warnings-from-preventdefault-after-i-pass--passive-false-).

Note sure what's wrong with the example?

**Comment by rejifald** [comment]
Thank you for the link.
In the example when I try zoom picture, it also scales whole page.
I am using macbook touchpad to zoom.
Also, there error in console.

**Comment by dbismut** [comment]
What browser are you using?

**Comment by rejifald** [comment]
Google Chrome. I can capture a video. Will it help ?

**Comment by dbismut** [comment]
That's fine! I've fixed the sandbox, you can check the link again and it should work ok ;)

**Comment by rejifald** [comment]
It works ok !
Please, help me, I don't understand why it doesn't work in my code.
```
function Component ( ) {
        document.addEventListener('gesturestart', e => e.preventDefault());	 
        document.addEventListener('gesturechange', e => e.preventDefault());

        const ref = useRef();
	const bindPinch = usePinch(({ event }) => {
		event.preventDefault();
	}, {
		event: { passive: false },
		domTarget: ref,
	});

	return (
		<animated.div
			{...bindPinch()}
			ref={ref}
		>
                 ...
		</animated.div>
	);
}
```

**Comment by rejifald** [comment]
I have this error
`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312`

**Comment by dbismut** [comment]
When using the `domTarget` option you can't spread the `bind` object to the component. You need to use `React.useEffect` as [explained here](https://github.com/react-spring/react-use-gesture#adding-gestures-to-dom-nodes).

```jsx
React.useEffect(bindPinch, [bindPinch])
```

**Comment by dbismut** [comment]
Also, in your example you should make sure to remove `gesture` listeners when the component unmounts.

**Comment by rejifald** [comment]
It works. Appreciate your help !
