### ISSUE TITLE
support for SSR

### ISSUE THREAD

**Issue by AlQa-hOlic** [react-spring/react-use-gesture#89]
**TypeError: Cannot convert undefined or null to object**

```
import { useGesture } from 'react-use-gesture';
   4 | 
   5 | export function Slider({ value, min, max, step, onChange }) {
> 6 |     const [bind, { delta, down }] = useGesture();
   7 | 
   8 |     const { x } = useSpring({
....
```

is this happening because `window` is undefined?

**Comment by dbismut** [comment]
This happens because you’re not using the API properly. Have a look at the docs and let me know if your troubles persist.
