### ISSUE TITLE
New exemple available but can't fix boudaries

### ISSUE THREAD

**Issue by mhamel** [react-spring/react-use-gesture#90]
Hi!

I've made an exemple on sandbox but there is one thing I can't figure out: set boudaries with acceleration enable.  I think this would be a good addition to your exemples.

https://codesandbox.io/s/blissful-lichterman-d4r2s?fontsize=14

**Comment by dbismut** [comment]
Hey @mhamel I'm really not sure of what you're trying to achieve, but from what I understand, is more related to react-spring than this lib. If it helps, here is a codesandbox that simulates inertia with bounce on boundaries. With the final release of react-spring v9 the implementation should be greatly simplified.
