### ISSUE TITLE
Demo wont run locally

### ISSUE THREAD

**Issue by rhulse** [react-spring/react-use-gesture#91]
Hi.

I used the code from [this official demo](https://codesandbox.io/embed/n9vo1my91p) as the basis of some work in a project, but the drag did not work at all.

So I copied the demo cleanly into a new create-react-app project (which is what I'm using) and the drag still does not work. If I change the useGesture hook to explicitly use `onDrag` it sort of works. The picture scales down as I drag, but does not move until I get to a certain point and then it slides. I can see the numbers in transform() starting to go up, and as soon as I stop dragging they go down again. 

I've been trying to work out what is going on for longer than I care to admit.

This is on Chrome Version 77.0.3865.90 (Official Build) (64-bit). 

Here is my packages.json:
```json
{
  "name": "swipe-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "lodash-es": "^4.17.15",
    "react": "^16.10.0",
    "react-dom": "^16.10.0",
    "react-spring": "^8.0.27",
    "react-use-gesture": "^6.0.1"
  },
  "devDependencies": {
    "react-scripts": "3.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

I also tried downgrading to React v 16.9.0

**Comment by rhulse** [comment]
I've found the issue, as one often does after writing it down. ;-)

 I did not check the version of react-use-gesture, and upon looking at the change log I spied breaking changes, and I have now got this fixed. The fix (for anyone else looking) is to simply to replace `delta: [xDelta]` with `movement: [xDelta]`, and put the block into `onDrag`.

**Comment by dbismut** [comment]
Indeed I need to work with @aleclarson and @drcmda to use the same sandboxed demos for react-spring and react-use-gesture (mine are up to date, just sayin’ 🙉

**Comment by rhulse** [comment]
@dbismut No worries - I needed a 'bug' to help me get a better understanding of how to use the library anyway. 😺 This stuff is fantastic, team!
