### ISSUE TITLE
usePinch 'origin' is always [0, 0]

### ISSUE THREAD

**Issue by patrickherrmann** [react-spring/react-use-gesture#92]
Repro: https://codesandbox.io/embed/react-use-gesture-template-zk203
(Note `console.log(origin)` always outputs `[0, 0]`)

Not sure if I understand this property, but I'd expect origin to be the coordinates where the pinch started, and possibly see it drift if the pinch gesture is not perfectly symmetrical. Is that the right assumption?

Edit: I'm realizing now that it's because I'm using a trackpad, not touching the actual screen.
Is there a way to get the cursor position during pinch? This would be useful in order to zoom in on the right spot.

**Comment by dbismut** [comment]
Hey @patrickherrmann, I've just released `6.0.3` which sets origin to cursor position when using trackpad. It should work with wheel zoom (ie Mac trackpad and Chrome) or gesture events (ie Mac trackpad and Safari).

**Comment by patrickherrmann** [comment]
That works beautifully, thanks for the extremely fast release!
