### ISSUE TITLE
usePinch to redirect example

### ISSUE THREAD

**Issue by NickCarducci** [react-spring/react-use-gesture#93]
Hey react-use-gesture contributors,
Can you help with this usePinch to redirect (redirect = react-router's this.props.history.push('/')) example?
I'm sure this isn't an issue, just with me not using it correctly.
I made this [codesandbox](https://codesandbox.io/s/cool-silence-oezmi) for you.
Your response would help so much!
btw, I'm going to usePinch for this on every page of my app.

````const Login = () => {
  const binding = usePinch(({d}) => { (d < 40) ? this.props.history.push('/'):null})
    return (
      <div {...binding()}>
        <img
          className="alternative"
          src="https://www.dl.dropboxusercontent.com/s/9ctrgn3angb8zz4/Screen%20Shot%202019-10-02%20at%2011.30.21%20AM.png?dl=1"
          alt="error"
        />
      </div>
    );
  }

export default Login
````

**Comment by dbismut** [comment]
@NickCarducci I'm not sure how great idea this is to use pinch to deal with routing, but anyway! I'll also just focus on your specific question. Here is the code you might want to use:

```jsx
const Login = () => {
  const el = React.useRef();
  const binding = usePinch(
    ({ movement: [d], last }) => {
      if (last && d < -40) {
        this.props.history.push('/')
      }
    },
    { domTarget: el, event: { passive: false } }
  );
  React.useEffect(binding, [binding]);

  return (
    <div ref={el}>
      <img
        className="alternative"
        src="https://www.dl.dropboxusercontent.com/s/9ctrgn3angb8zz4/Screen%20Shot%202019-10-02%20at%2011.30.21%20AM.png?dl=1"
        alt="error"
      />
    </div>
  );
};
```

I'm using refs as usePinch with trackpads works better when the event is prevented (which is not possible when binding the component directly as React only supports passive events handlers).

Depending on whether you want to pinch or unpinch you might want to use `d < -40` or `d > 40`.
 
Let me know if anything else is unclear.

**Comment by NickCarducci** [comment]
Beautiful snippet there thank you... just to get the example for future readers working (and me ha...): when I pinch on it and get error `undefined is not an object (evaluating '_this.props')`... Does this mean it's an issue with my BrowserRouter configuration?  this.props.history.push('/') should work inside BrowserRouter

**Comment by dbismut** [comment]
I’ve just copy pasted your code but indeed since this is a functional component this.props doesn’t exist. But this is clearly outside the scope of this lib sorry.

**Comment by NickCarducci** [comment]
No problem thanks!
