### ISSUE TITLE
Simple example "xyz.to" is not a function

### ISSUE THREAD

**Issue by impulse** [react-spring/react-use-gesture#94]
`TypeError: xy.to is not a function`

Used dependencies

```
    "react": "16.10.2",
    "react-dom": "16.10.2",
    "react-scripts": "3.2.0",
    "react-spring": "8.0.27",
    "react-use-gesture": "6.0.3",
```

Replacing `xy.to` with `xy.interpolate` works fine

**Comment by dbismut** [comment]
Hey @impulse, examples use `react-spring` beta `v9` as it has a simpler API and should be released pretty soon. `interpolate` is replaced with `to` and `animated` accepts simple transform props in its style attribute ([see here](https://github.com/react-spring/react-spring/pull/782)). 

I should probably have written a warning but v9 is really on the edge of being released!

**Comment by impulse** [comment]
Oh wow this looks way better, thanks for letting me know @dbismut 👍🏻
