### ISSUE TITLE
onWheel direction bug?

### ISSUE THREAD

**Issue by LJEsp** [react-spring/react-use-gesture#97]
When using the scroll wheel very slowly (as if reading an article), the direction doesn't update: 
![image](https://user-images.githubusercontent.com/36854142/66728436-7bf9d400-ee77-11e9-9295-1bddb757e9fc.png)
But it updates if I scrolled stronger.

Currently I just use state.event.deltaY as a workaround.

**Comment by dbismut** [comment]
Hi @LJEsp thanks for reporting this issue, it’s actually linked to #96, I forgot to fix some state attributes.  I’ll release a fix today. Sorry about this!

**Comment by dbismut** [comment]
This should be fixed in `6.0.10`!
