### ISSUE TITLE
viewpager() example to typescript

### ISSUE THREAD

**Issue by kristkirp** [react-spring/react-use-gesture#99]
Hi guys,

I'm trying to use this drag animation in typescript https://codesandbox.io/s/viewpager-sq9ud

And I'm stuck at this line:
```javascript
set((i) => {
        if (i < index.current - 1 || i > index.current + 1) return { display: 'none' };
        const x = (i - index.current) * window.innerWidth + (down ? mx : 0);
        return { x, display: 'block' };
      });
```

![image](https://user-images.githubusercontent.com/30670856/67106777-3c91f700-f199-11e9-8f8e-1144e02dcd15.png)

And it gives me this error:
>No overload matches this call.
  Overload 1 of 2, '(ds: Partial<Merge<{ x: number; display: string; } & UseSpringBaseProps, { from?: Partial<Pick<{ x: number; display: string; }, "display" | "x">> | undefined; onRest?(ds: Partial<Pick<{ x: number; display: string; }, "display" | "x">>): void; }>>): void', gave the following error.
    Value of type '(i: any) => { display: string; x?: undefined; } | { x: number; display: string; }' has no properties in common with type 'Partial<Merge<{ x: number; display: string; } & UseSpringBaseProps, { from?: Partial<Pick<{ x: number; display: string; }, "display" | "x">> | undefined; onRest?(ds: Partial<Pick<{ x: number; display: string; }, "display" | "x">>): void; }>>'. Did you mean to call it?
  Overload 2 of 2, '(i: number): Partial<Merge<{ x: number; display: string; } & UseSpringBaseProps, { from?: Partial<Pick<{ x: number; display: string; }, "display" | "x">> | undefined; onRest?(ds: Partial<Pick<{ x: number; display: string; }, "display" | "x">>): void; }>>', gave the following error.
    Argument of type '(i: any) => { display: string; x?: undefined; } | { x: number; display: string; }' is not assignable to parameter of type 'number'.ts(2769)
Carousel.tsx(127, 11): Did you mean to call this expression?

Thank you

**Comment by dbismut** [comment]
Hi @kristkirp, closing since this looks like a react-spring issue.
